"""File manager custom actions (~/.config/Thunar/uca.xml) + the `link` helper script they call.

The file manager's "Custom Actions" are a first-class feature: uca.xml lists actions, each with
a shell <command> and CONDITIONS (a filename <patterns> glob plus type flags -- <directories/>,
<image-files/>, <text-files/>, <audio-files/>, <video-files/>, <other-files/> -- that decide
when the action appears in the right-click menu). %f/%F substitute the selected path(s), %d
the parent directory. This module ships a FULL uca.xml (it REPLACES the stock example file --
the file manager reads the user's ~/.config/Thunar/uca.xml in full, it is not merged with the
system /etc/xdg/Thunar/uca.xml) with exactly the actions Azzio wants (PROMPT task 2):

  1. Edit with gimp    -- on IMAGE files only (<image-files/>), runs `gimp %F`.
  2. Create Link ...    -- on a directory / folder BACKGROUND (<directories/> + the current
                          folder), prompts for a name + target via zenity and runs the `link`
                          helper (below) in that folder.
  3. Open Terminal Here -- on any folder / background, opens kitty (the Azzio terminal) in
                          the directory. We run kitty DIRECTLY rather than
                          `exo-open --launch TerminalEmulator`, because Arch's exo ships no
                          helper stack; the exo TerminalEmulator helper is ALSO pointed at
                          kitty by packages/azzio/default_applications.py as belt-and-braces.

XML SCHEMA (verified against the installed file manager's /etc/xdg/Thunar/uca.xml + what the
file manager writes back): the DOCTYPE/`<actions>` wrapper, and inside each `<action>` the
child ORDER icon, patterns, name, unique-id, command, description, then the type-condition empty
elements. <unique-id> is any stable string (the file manager uses a timestamp-counter; we use
fixed ids -- the build has no clock and the file manager does not require uniqueness across
machines, only within the file). <startup-notify/> asks the launcher feedback cursor.

THE `link` HELPER (PROMPT task 2, verbatim behaviour). A shell FUNCTION cannot be exec'd by a
custom action, so the logic ships as a real script at LINK_SCRIPT_DEST (root-owned, 0755,
system-wide). Given `link <name> <target>`:
  * target is a URL (scheme:// or www.*) -> write a `<name>.html` redirect file that
    window.location's to the URL.
  * target is a path (anything else)     -> create a symlink `<name>` -> target (realpath'd
    if it exists).
The Create Link action wraps it: zenity prompts for the name and the target, then the script
runs with the folder as the working directory (`--working-directory %f` semantics via `cd`).

WHY THERE IS NO "Edit with gedit" CUSTOM ACTION HERE (PROMPT batch item 7). The file manager's
context menu ALREADY shows the built-in default-opener at the very top: for a text file whose
default is gedit it reads `Open With "gedit"`. Shipping our OWN "Edit with gedit" uca action
produced a SECOND, duplicate entry. The fix keeps exactly ONE entry, at the top, literally
"Edit with gedit" (no quotes): the gettext .mo override (packages/file_manager/locale) relabels
the built-in format `_Open With "%s"` to `_Edit with %s`, so that top item renders "Edit with
gedit" -- and we DROP the custom gedit action to avoid the duplicate. "Edit with gimp" stays a
uca action (images only), since gimp is not a default handler and would otherwise not appear.

compiler._emit_apps ships uca.xml as a HOME file (owner "home", skel-mirrored) and the `link`
script as a root-owned system file (owner "root").
"""

from __future__ import annotations

from xml.sax.saxutils import escape as _xml_escape

# The live user's home (matches openbox.HOME / the airootfs /home/main tree).
HOME = "/home/main"

# Where the file manager reads the user's custom actions. Shipping this REPLACES the stock
# example (the file manager reads ~/.config/Thunar/uca.xml in full).
UCA_PATH = f"{HOME}/.config/Thunar/uca.xml"

# The `link` helper script (a real script -- a shell function cannot be exec'd by a custom
# action). System-wide, root-owned, executable; the Create Link action calls it by this path.
LINK_SCRIPT_DEST = "/usr/local/bin/azzio-link"

# The Azzio terminal the "Open Terminal Here" action opens (run directly -- Arch's exo has
# no helper stack). kitty's `--working-directory` opens it in the folder.
TERMINAL_BIN = "kitty"


def link_script() -> str:
    """Return the `link` helper installed at LINK_SCRIPT_DEST. This is the PROMPT's shell
    function turned into a standalone script (a function cannot be exec'd by a custom
    action): URL target -> write a <name>.html redirect; path target -> make a symlink
    <name> -> target (realpath'd if it exists). Runs in the current working directory (the
    Create Link action cd's into the selected folder first)."""
    return """\
#!/usr/bin/env bash
# Azzio `link` helper. Generated by packages/file_manager (edit the Python, not this file).
# The file manager's "Create Link" custom action calls this after prompting (via zenity) for a
# name and a target, with the working directory set to the folder the action was invoked in.
#
#   link <name> <target>
#     target is a URL  (scheme:// or www.*) -> writes a <name>.html redirect file
#     target is a path (anything else)       -> creates a symlink  <name> -> target
set -u
link() {
    if [ "$#" -lt 2 ]; then
        echo "usage: link <name> <path-or-url>" >&2
        return 1
    fi
    local name="$1" target="$2"
    if [[ "$target" =~ ^[a-zA-Z][a-zA-Z0-9+.-]*:// ]] || [[ "$target" == www.* ]]; then
        echo '<script>window.location.href = "'"$target"'";</script>' > "$name.html"
        echo "redirect: $name.html -> $target"
    else
        [ -e "$target" ] && target="$(realpath -- "$target")"
        ln -s -- "$target" "$name" && echo "symlink: $name -> $target"
    fi
}
link "$@"
"""


# --- uca.xml -------------------------------------------------------------------
# The Create Link command: prompt for a name, then a target, via zenity (both must be
# non-empty), cd into the selected folder (%f) and run the `link` helper. Written as a single
# shell command line (uca <command> is run via /bin/sh -c). zenity --entry returns the typed
# text on stdout and a non-zero status on Cancel, so `|| exit 0` aborts cleanly on cancel.
_CREATE_LINK_COMMAND = (
    "sh -c '"
    'name=$(zenity --entry --title="Create Link" '
    '--text="Link name:") || exit 0; '
    "[ -z \"$name\" ] && exit 0; "
    'target=$(zenity --entry --title="Create Link" '
    '--text="Target (website URL, or a file/directory path):") || exit 0; '
    "[ -z \"$target\" ] && exit 0; "
    'cd "$1" || exit 1; '
    f'"{LINK_SCRIPT_DEST}" "$name" "$target"'
    "' _ %f"
)


def uca_xml() -> str:
    """Return ~/.config/Thunar/uca.xml -- the full custom-actions file (REPLACES the stock
    example). Actions, in menu order: Edit with gimp (images), Create Link (folder/background),
    Open Terminal Here (folder/background). "Edit with gedit" is deliberately NOT a uca action
    (see the module docstring, PROMPT batch item 7): it comes from the built-in default-opener,
    relabelled to "Edit with gedit" by the gettext .mo override, so there is no duplicate. The
    child-element order and condition tags match the file manager's schema (verified against the
    file manager).

    The `link` helper is invoked by absolute path (LINK_SCRIPT_DEST); the terminal action runs
    kitty directly with --working-directory. unique-ids are fixed (the build has no clock;
    the file manager only needs them unique within this file).

    NOTE the <range></range> element after <patterns> on EVERY action: it is REQUIRED for the
    folder-only actions (Create Link, Open Terminal Here) to appear on the folder BACKGROUND
    (the current directory with nothing selected) -- verified against the file manager 4.20:
    WITHOUT <range/> those actions only show when a directory is explicitly selected, exactly as
    the stock "Open Terminal Here" ships it. It is harmless on the gimp file action, so it is on
    all of them for a uniform, stock-matching schema."""
    # XML-escape command bodies: the Create Link command contains shell `&&`, and `&`/`<`/`>`
    # are invalid raw in XML text -- an unescaped `&&` makes the WHOLE file not well-formed, so
    # the file manager's parser stops there and silently drops that action AND every action after
    # it (verified: this is why Create Link + Open Terminal Here vanished until the `&&` was
    # escaped). The file manager un-escapes when it reads the command back. gedit/gimp/kitty
    # commands have no special chars, but escaping all of them is uniform and correct.
    create_link_cmd = _xml_escape(_CREATE_LINK_COMMAND)
    terminal_cmd = _xml_escape(f"{TERMINAL_BIN} --working-directory %f")
    return f"""\
<?xml version="1.0" encoding="UTF-8"?>
<!-- Azzio file-manager custom actions. Generated by packages/file_manager (edit the Python, not
     this file). REPLACES the stock example uca.xml (the file manager reads this file in full). -->
<actions>
  <action>
    <icon>gimp</icon>
    <patterns>*</patterns>
    <range></range>
    <name>Edit with gimp</name>
    <unique-id>azzio-edit-gimp-2</unique-id>
    <command>gimp %F</command>
    <description>Open this image in GIMP</description>
    <startup-notify/>
    <image-files/>
  </action>
  <action>
    <icon>emblem-symbolic-link</icon>
    <patterns>*</patterns>
    <range></range>
    <name>Create Link (Website URL or Directory or File)</name>
    <unique-id>azzio-create-link-3</unique-id>
    <command>{create_link_cmd}</command>
    <description>Create a symlink, or an HTML redirect for a website URL, in this folder</description>
    <startup-notify/>
    <directories/>
  </action>
  <action>
    <icon>utilities-terminal</icon>
    <patterns>*</patterns>
    <range></range>
    <name>Open Terminal Here</name>
    <unique-id>azzio-open-terminal-4</unique-id>
    <command>{terminal_cmd}</command>
    <description>Open the Azzio terminal (kitty) in this folder</description>
    <startup-notify/>
    <directories/>
  </action>
</actions>
"""
