"""Azzio File Manager launcher override -- rename to "File Manager" + a custom Azzio icon.

THE .DESKTOP (thunar.desktop). The thunar package ships /usr/share/applications/thunar.desktop
with Name="Thunar File Manager" and Icon=org.xfce.thunar (verified on the installed system).
Azzio overrides it so the application menu shows "File Manager" with the Azzio icon:

  * Name = "File Manager"   (not "Thunar File Manager")
  * Icon = FILE_MANAGER_ICON_NAME (our custom icon, see below), not org.xfce.thunar
  * StartupWMClass = Thunar  (the running window's WM_CLASS): pins the window switcher's
    window->.desktop resolver to THIS launcher via the primary (StartupWMClass) match, so the
    Alt-Tab tile shows the custom icon without relying on the Exec-binary/id-stem fallback.
  * Everything else (Exec=thunar %U, the open-home/open-computer/open-trash Actions, MimeType
    inode/directory, Categories, StartupNotify) kept as the package ships it. The .desktop
    FILENAME stays thunar.desktop (the package owns that path and the binary is still `thunar`);
    only the human-visible Name, the Icon, and the added StartupWMClass change.

This is a PACKAGE-OWNED file, so -- exactly like gedit's org.gnome.gedit.desktop -- it cannot
be pre-placed in the airootfs overlay (pacstrap's file-conflict check would abort). It is
NoExtract'd (pacman.ISO_APP_OVERRIDES) and planted after pacstrap by app_override_cp_sh(); the
emit_plan() entry's dest matches an ISO_APP_OVERRIDES target, so compiler._emit_apps stages
the body under root/azzio/apps/ instead of writing it into the overlay.

THE ICON (assets/icons/file_manager.svg). A clean folder in the Azzio blue-gradient-on-dark badge
(the same visual identity as assets/icons/azzio.svg / kitty.svg). The icon is shipped the
SAME way kitty's is: the SVG asset is the single source of truth; we ship it to the hicolor
SCALABLE apps dir under our OWN icon name (FILE_MANAGER_ICON_NAME) and rasterize it to the standard
PNG sizes there too, and the .desktop's Icon= points at that name. We use a NEW icon NAME
(azzio-file-manager) rather than overwriting org.xfce.thunar, so a thunar package upgrade that
reships org.xfce.thunar cannot revert our icon -- our name is ours alone. (kitty had to reuse
its own name because kitty's binary hard-codes it; the file manager reads Icon= from the
.desktop we own, so a private name is cleaner here.)

ICON FILES ARE NOT PACKAGE-OWNED (our name is new), so they go in the airootfs overlay
directly (owner "root") -- no NoExtract needed, unlike the .desktop.

compiler._emit_apps handles this module's emit_plan(): the .desktop (builder, redirected to
the app-override staging dir), the scalable SVG ("asset" copy), and the PNG rasterizations
("render"). The icon-name override is what makes the menu tile show the Azzio folder.
"""

from __future__ import annotations

# --- The .desktop override ------------------------------------------------------
# Package-owned path (thunar), so this dest is also listed in pacman.ISO_APP_OVERRIDES and
# NoExtract'd; compiler._emit_apps stages the body for the post-pacstrap install hook.
FILE_MANAGER_DESKTOP_PATH = "/usr/share/applications/thunar.desktop"

# --- The custom icon ------------------------------------------------------------
# The single-source-of-truth SVG asset (referenced by path like kitty's icon), and OUR icon
# name (new, so a thunar upgrade cannot revert it). The .desktop Icon= points at this name.
ICON_ASSET = "icons/file_manager.svg"
FILE_MANAGER_ICON_NAME = "azzio-file-manager"
# Where the icon loader resolves FILE_MANAGER_ICON_NAME: the hicolor scalable master (our SVG) plus
# PNG rasterizations at the standard sizes (so every surface -- menu tile, Alt-Tab, window
# icon -- has a source without a theme-cache rebuild). Not package-owned (new name) -> overlay.
ICON_SCALABLE_PATH = f"/usr/share/icons/hicolor/scalable/apps/{FILE_MANAGER_ICON_NAME}.svg"
ICON_PNG_SIZES = (16, 22, 24, 32, 48, 64, 128, 256)
ICON_PNG_DIR = "/usr/share/icons/hicolor/{size}x{size}/apps"


def file_manager_desktop() -> str:
    """/usr/share/applications/thunar.desktop -- the renamed launcher with the Azzio icon.

    Name="File Manager" and Icon=azzio-file-manager; Exec, the three Desktop Actions, MimeType,
    Categories and StartupNotify are kept exactly as the thunar package ships them (only the
    Name and Icon change). DBusActivatable is not set (the default launch is fine)."""
    return f"""\
[Desktop Entry]
# Azzio File Manager launcher override. Generated by packages/file_manager (edit the Python, not
# this file). Renames "Thunar File Manager" to "File Manager" and points Icon at the custom
# Azzio icon ({FILE_MANAGER_ICON_NAME}); everything else is stock thunar.desktop.
Name=File Manager
Comment=Browse the filesystem with the file manager
GenericName=File Manager
Exec=thunar %U
Icon={FILE_MANAGER_ICON_NAME}
Terminal=false
StartupNotify=true
StartupWMClass=Thunar
Type=Application
Categories=System;Core;GTK;FileTools;FileManager;
MimeType=inode/directory;
Actions=open-home;open-computer;open-trash;
Keywords=file manager;explorer;finder;browser;folders;directory;directories;home;trash;

[Desktop Action open-home]
Name=Home
Exec=thunar %U

[Desktop Action open-computer]
Name=Computer
Exec=thunar computer:///

[Desktop Action open-trash]
Name=Trash
Exec=thunar trash:///
"""
