"""File manager UI-string overrides via a gettext .mo catalog (PROMPT batch items 3, 7,
8-wording).

A few file manager menu labels are HARDCODED gettext strings in the binary (there is no config
/ xfconf / uca.xml lever for them -- verified against the file manager 4.20 source). The
supported, stable way to change them is a gettext message catalog: the file manager calls
`bindtextdomain("thunar", "/usr/share/locale")` and every menu label goes through `gettext()`,
so a `thunar.mo` under the ACTIVE locale's LC_MESSAGES dir that maps the exact msgid to our
wording wins -- no fighting hardcoded C++ (this is GTK/gettext, the intended mechanism).

WHAT WE OVERRIDE (each msgid is the EXACT string from the 4.20 binary; the mnemonic `_` and the
`...` ellipsis are part of the msgid and must match byte-for-byte or gettext falls through to
the original):

  * '_Open With "%s"'   -> "_Edit with %s"     (batch item 7: the built-in default-opener at the
        top of the context menu -- for a text file whose default is gedit it reads
        `Open With "gedit"`. Overriding the format to `Edit with %s` makes that top item read
        `Edit with gedit` with NO quotes. Our own uca "Edit with gedit" duplicate is DROPPED
        (see actions.py) so exactly ONE such entry remains, at the top. The images-only "Edit
        with gimp" uca action stays.)
  * "Create _Folder..." -> "Create New _Folder..."    (batch item 8 wording)
  * "Create _Document"  -> "Create New _Document..."   (batch item 8 wording; the base label
        carries no ellipsis in the msgid, we add it to match "Create New Folder...")

WHICH LOCALE ACTUALLY APPLIES. gettext only consults the catalog in the LC_MESSAGES dir of the
locale that is IN EFFECT (a common myth is that English msgids ignore catalogs; that is TRUE
ONLY for the C/POSIX locale -- for a REAL generated locale glibc's gettext DOES consult it).
The catch: the DEFAULT installed Azzio system does NOT run en_US. calamares seeds the region
as Asia/Jerusalem (packages/calamares/calamares.locale_conf), so out of the box the target's
/etc/locale.conf is LANG=en_IL (English/Israel) -- VERIFIED on the live hypervisor: openbox's
environ has LANG=en_IL and `LANG=en_IL gettext -d thunar "Places"` returned the STOCK "Places"
until an en_IL catalog was present, then returned "Home". So a catalog shipped ONLY under en_US
never applies for the default user. We therefore ship the SAME catalog under en_US (if the user
picks a US region on the locale page), en_GB (the LC_TIME date locale), AND en_IL (the default
region's display locale) so whichever LC_MESSAGES is in effect finds it -- no LANGUAGE tricks, no
whole-desktop locale change. All three are generated by locale-gen here.

THE .mo IS GENERATED IN PURE PYTHON (mo_bytes()) -- the standard GNU .mo binary format (a tiny,
well-specified table of msgid/msgstr offsets). No external `msgfmt` dependency, deterministic
(so a test can pin the bytes), and it slots into the emit machinery as a binary blob.

compiler._emit_apps ships the .mo as a ROOT-owned system file at each locale path (it is a
system locale catalog, not a per-user dotfile) -- so every user on the installed system gets
the relabelled file manager. (Delivered via the "mo" plan-entry kind that compiler writes
verbatim.)

IMPORTANT -- the en_GB catalog path is OWNED BY THE `thunar` PACKAGE. `thunar` ships 67 locale
catalogs including /usr/share/locale/en_GB/LC_MESSAGES/thunar.mo. pacman's file-conflict check
runs BEFORE extraction (and is NOT suppressed by NoExtract), so pre-placing our en_GB catalog in
the airootfs overlay aborts pacstrap with "thunar.mo exists in filesystem". Both locale dests are
therefore routed through pacman.ISO_APP_OVERRIDES (NoExtract + post-pacstrap install) exactly like
the .desktop overrides -- see mo_path()/LOCALES wired into ISO_APP_OVERRIDES and the compiler's
_override_basename redirect. (en_US carries no package catalog -- the file manager's msgids ARE
American English -- so it never conflicts, but travels the same path for symmetry.)
"""

from __future__ import annotations

import struct

# The locales the Azzio ISO generates (packages/calamares/locale): en_US.UTF-8 is the
# display language, en_GB.UTF-8 the LC_TIME date locale. Ship the override catalog under BOTH
# so whichever LC_MESSAGES is in effect finds it. The catalog dir is the standard system path
# the file manager's bindtextdomain uses.
LOCALES: tuple[str, ...] = ("en_US", "en_GB", "en_IL")
TEXTDOMAIN = "thunar"


def mo_path(locale: str) -> str:
    """Absolute system path of the file manager's override catalog for a locale (the standard
    /usr/share/locale/<locale>/LC_MESSAGES/<domain>.mo the file manager's bindtextdomain reads)."""
    return f"/usr/share/locale/{locale}/LC_MESSAGES/{TEXTDOMAIN}.mo"


# The exact msgid -> our-wording map. Keys are the EXACT strings from the file manager 4.20
# binary (mnemonics and ellipses included) -- a byte mismatch means gettext falls through to the
# original, so these must not be "cleaned up". VERIFIED via `strings /usr/bin/thunar`.
OVERRIDES: dict[str, str] = {
    # The shortcuts sidebar section header. The file manager's built-in header msgid is "Places"
    # (verified via `strings /usr/bin/thunar`); the user wants it to read "Home". It is a
    # hardcoded gettext string (no xfconf/config lever), so the catalog is the supported way to
    # rename it.
    "Places": "Home",
    '_Open With "%s"': "_Edit with %s",
    "Create _Folder...": "Create New _Folder...",
    "Create _Document": "Create New _Document...",
    # App identity: relabel the product name "Thunar" -> "File Manager" wherever the binary
    # emits it as a gettext-wrapped display string (verified as standalone msgids in the vendored
    # source/po catalogs). The application name (g_set_application_name(_("Thunar"))), the
    # Preferences window title, and the About-dialog blurb. The window TITLE-BAR suffix is a bare
    # C literal (not gettext), so it is relabelled directly in the vendored thunar-window.c, not
    # here. "Thunar Bulk Rename" is left as-is (that sub-tool's own feature name).
    "Thunar": "File Manager",
    "Thunar Preferences": "File Manager Preferences",
    "Thunar is a fast and easy to use file manager\n"
    "for the Xfce Desktop Environment.":
        "File Manager is a fast and easy to use file manager\n"
        "for the Xfce Desktop Environment.",
}


def mo_bytes() -> bytes:
    """Return the GNU .mo binary catalog for OVERRIDES (domain `thunar`).

    Implements the documented GNU MO format (little-endian): magic 0x950412de, revision 0,
    a count N, the offsets of the msgid and msgstr string tables, then N (length, offset)
    pairs for the sorted msgids followed by N pairs for the msgstrs, then the string data.
    msgids MUST be sorted (gettext binary-searches them). A leading empty-string entry with a
    minimal header is conventional; we include it so the catalog is well-formed and carries the
    charset. Pure standard library (struct), deterministic -- a test pins the round-trip."""
    # The empty msgid maps to the catalog header (charset etc.), per the GNU format.
    header = "Content-Type: text/plain; charset=UTF-8\n"
    entries = {"": header}
    entries.update(OVERRIDES)
    # Sort by msgid bytes (gettext requires sorted keys for its binary search).
    keys = sorted(entries.keys(), key=lambda k: k.encode("utf-8"))
    ids = b""
    strs = b""
    id_table: list[tuple[int, int]] = []   # (length, offset) into the ids blob
    str_table: list[tuple[int, int]] = []
    for k in keys:
        kb = k.encode("utf-8")
        vb = entries[k].encode("utf-8")
        id_table.append((len(kb), len(ids)))
        ids += kb + b"\x00"                 # NUL-terminated (length excludes the NUL)
        str_table.append((len(vb), len(strs)))
        strs += vb + b"\x00"
    n = len(keys)
    # Layout: 7 uint32 header, then the two tables (each n*2 uint32), then the string blobs.
    header_size = 7 * 4
    id_table_off = header_size
    str_table_off = id_table_off + n * 8
    ids_off = str_table_off + n * 8
    strs_off = ids_off + len(ids)
    out = bytearray()
    out += struct.pack("<Iiiiiii",
                       0x950412de,   # magic
                       0,            # file format revision
                       n,            # number of strings
                       id_table_off, # offset of table with original strings
                       str_table_off,# offset of table with translated strings
                       0,            # size of hashing table (unused)
                       0)            # offset of hashing table (unused)
    for length, off in id_table:
        out += struct.pack("<II", length, ids_off + off)
    for length, off in str_table:
        out += struct.pack("<II", length, strs_off + off)
    out += ids
    out += strs
    return bytes(out)
