"""Application-menu cleanup -- hide the extra file-manager/Xfce launchers.

Installing Azzio File Manager (the `thunar` package) and its companions drops several .desktop
launchers into the application menu that Azzio does NOT want cluttering it:

  * thunar-bulk-rename.desktop      "Bulk Rename"              (owned by thunar)
  * thunar-settings.desktop         "Thunar Preferences"      (owned by thunar)
  * xfce4-about.desktop             "About Xfce"              (owned by libxfce4ui)

(Ownership VERIFIED on the installed system via `pacman -Qo`.) These are hidden by shipping an
override .desktop with NoDisplay=true for each -- the standard freedesktop way to keep a
launcher out of menus while leaving the app installed and runnable. The Azzio application
menu honours NoDisplay (applications.c reads the NoDisplay key and skips the entry), as does
every other XDG menu, so this hides them everywhere. This is the SAME NoExtract + override
pattern the repo already uses for package-owned files (gedit's .desktop, kitty's icon):
these paths are package-owned, so they are NoExtract'd (pacman.ISO_APP_OVERRIDES) and the
NoDisplay bodies are planted post-pacstrap by app_override_cp_sh().

Each override keeps the original Name/Exec/Icon (so nothing else about the app changes) and
only ADDS NoDisplay=true. compiler._emit_apps stages each body (its dest matches an
ISO_APP_OVERRIDES target) for the install hook.
"""

from __future__ import annotations

# The package-owned launchers Azzio hides, keyed by their .desktop basename. Each value is
# (original Name, original Exec, original Icon) -- kept verbatim in the override so only
# NoDisplay changes. VERIFIED against the installed .desktop files (thunar 4.20 / libxfce4ui).
# The system path is /usr/share/applications/<basename>.
_APPLICATIONS_DIR = "/usr/share/applications"
SUPPRESSED: tuple[tuple[str, str, str, str], ...] = (
    # basename,                         Name,                          Exec,                       Icon
    ("thunar-bulk-rename.desktop",      "Bulk Rename",                 "thunar --bulk-rename %F",  "org.xfce.thunar"),
    ("thunar-settings.desktop",         "Thunar Preferences",          "thunar-settings",          "org.xfce.thunar"),
    ("xfce4-about.desktop",             "About Xfce",                  "xfce4-about",              "org.xfce.xfce4-about"),
)


def suppressed_paths() -> list[str]:
    """Return the absolute /usr/share/applications paths of the launchers we hide (so
    pacman.ISO_APP_OVERRIDES and the emit plan agree on the targets)."""
    return [f"{_APPLICATIONS_DIR}/{basename}" for basename, _n, _e, _i in SUPPRESSED]


def _nodisplay_desktop(name: str, exec_line: str, icon: str) -> str:
    """Return a minimal override .desktop that hides the launcher (NoDisplay=true) while
    keeping the original Name/Exec/Icon so the app itself is unchanged (only removed from the
    menu). NoDisplay=true is the freedesktop "do not show in menus" key the Azzio menu and
    all XDG menus honour."""
    return f"""\
[Desktop Entry]
# Azzio override -- hide this launcher from the application menu (NoDisplay=true).
# Generated by packages/file_manager (edit the Python, not this file). The app stays installed
# and runnable; it just does not clutter the menu.
Type=Application
Name={name}
Exec={exec_line}
Icon={icon}
Terminal=false
NoDisplay=true
"""


def builders() -> list[tuple[str, str]]:
    """Return (dest_path, body) pairs for each hidden launcher's NoDisplay override, so the
    file_manager emit_plan can turn them into owner="root" entries whose dest matches an
    ISO_APP_OVERRIDES target (staged for the post-pacstrap install hook)."""
    out: list[tuple[str, str]] = []
    for basename, name, exec_line, icon in SUPPRESSED:
        dest = f"{_APPLICATIONS_DIR}/{basename}"
        out.append((dest, _nodisplay_desktop(name, exec_line, icon)))
    return out
