"""
specification_classify -- tag every package in the closure with two things the graph needs
but that are not in the raw Arch metadata:

  edition  -- is this Stock Arch (something the stock archiso `releng` medium
              already pulls in), or an Azzio Component (something in the set
              ONLY because Azzio added it on top of that stock baseline)?
  category -- a single human-language role ("Desktop compositor", "File manager",
              "Network manager", ...) so the graph can be read and coloured by what
              each package *is*, not by its name.

Both are derived deterministically from real signals:
  * EDITION (two values) -- grounded in the real dependency graph. Azzio starts
    from the stock archiso `releng` package list (held in code as
    specification_stock_baseline.STOCK_PACKAGES, the ground-truth baseline) and adds
    packages on top. A package is
    `stock` if the stock releng closure already contains it, and `azzio`
    (an "Azzio Component") if it is in the set ONLY because of an Azzio
    addition -- i.e. it is not reachable from any stock releng root. This is
    computed by specification_resolve from the edges, not guessed from names.
  * AZZIO_CONFIGURED  -- the subset of Azzio Components the build demonstrably
    customises. Grounded in the build's own configuration-as-Python modules (the flat
    compiler modules in libraries/, and every package under libraries/packages/*/ -- both the
    ones we author and the upstream software we tailor): each entry says which package is
    touched and how. It no longer defines a separate edition;
    it is surfaced as a per-package sub-note on the Azzio-Component packages that
    carry Azzio-specific changes.
  * CATEGORY cascade   -- curated role map first (highest confidence), then Arch
    group membership, then name patterns, then a shared-library / description
    fallback. Every package lands in exactly one category; nothing is left blank.

Kept separate from specification_content (hand-written prose) and specification_resolve (pure graph
math) so the "what is this package, editorially" logic lives in one auditable place.
"""

import re

# --------------------------------------------------------------------------- #
# Azzio modifications: the subset of Azzio Components the build brands or
# reconfigures. This is NOT an edition -- it is a per-package sub-note shown on
# top of the `azzio` (Azzio-Component) edition.
#
# Source of truth: the build's own configuration-as-Python modules (flat compiler
# modules in libraries/, and every package under libraries/packages/*/ -- both the ones we
# author and the upstream software we tailor). Each package here is one those modules
# demonstrably brand, configure, theme, replace or remove. `note` is the concrete,
# user-facing reason. `archiso` is the build tool itself and is intentionally absent
# -- it never ships inside the ISO.
# --------------------------------------------------------------------------- #
AZZIO_CONFIGURED = {
    "fastfetch":        "Custom Az' ANSI logo + config.jsonc replace the stock Arch fetch output",
    "pacman":           "Azzio pacman.conf: custom SigLevel, hardcoded mirrors, offline [pacstrap-azzio-repo], NoExtract rules",
    "filesystem":       "Rebranded /usr/lib/os-release (Azzio Linux) and /etc/hostname",
    "systemd":          "Rebranded systemd-boot UEFI loader entries + two live-ISO oneshot service units",
    "grub":             "Installed and grub.cfg regenerated by the installer chroot step",
    "syslinux":         "Rebranded BIOS boot menu title and entries (Azzio Linux)",
    "sudo":             "Sudoers drop-ins: passwordless sudo for 'main', rootpw default",
    "ufw":              "Enabled with default reject-incoming / allow-outgoing policy",
}

# Packages Azzio removes from the running system after pacstrap. The KDE overhaul
# dropped the desktop, so nothing is pacman -R'd any more -- kept as an empty set so
# the classify() call site stays stable.
AZZIO_REMOVED = set()


def edition_of(pkg, stock_reachable):
    """Return one of exactly two editions: 'stock' or 'azzio'.

    stock   -- "Stock Arch": the package is already in the stock archiso `releng`
               closure (reachable from a stock releng root). Azzio inherits it;
               it is on the medium whether Azzio adds anything or not.
    azzio -- "Azzio Component": the package is in the set ONLY because of an
               Azzio addition -- it is NOT reachable from any stock releng root.
               These are the packages Azzio brings to the table (a chosen app,
               or a dependency that exists purely to support one).

    `stock_reachable` is the set of packages reachable from the stock releng
    manifest, computed once by specification_resolve over the real dependency edges.
    """
    return "stock" if pkg in stock_reachable else "azzio"


# --------------------------------------------------------------------------- #
# Category: one human-language role per package.
#
# Resolved by a priority cascade (first hit wins):
#   1. CURATED     -- exact package -> role, for the packages that define the OS.
#   2. GROUP_ROLE  -- Arch group membership (plasma, kf6, qt6, xorg, ...).
#   3. NAME_RULES  -- name prefix/substring patterns (qt6-*, lib*, vlc-plugin-*, ...).
#   4. DESC_RULES  -- keyword match against the package description.
#   5. shared-lib fallback (provides an .so) -> "Shared library"; else "System".
#
# Categories are plain English on purpose: the graph is meant to be readable by
# someone who does not know the package names.
# --------------------------------------------------------------------------- #

# Stable ordering + palette anchor for the legend / SVG. The colour is a hint the
# renderer may use; keep it deterministic and colour-blind-safe-ish.
CATEGORY_ORDER = [
    "Kernel & firmware",
    "Boot & init",
    "Core system",
    "Shell & CLI tools",
    "Desktop shell",
    "Window/compositor",
    "Desktop app",
    "GUI toolkit/framework",
    "Graphics & display",
    "Audio",
    "Networking",
    "Storage & filesystems",
    "Security & crypto",
    "Developer tools",
    "Language runtime",
    "Multimedia codec/player",
    "Fonts & icons",
    "Printing & scanning",
    "Bluetooth & devices",
    "Virtualization guest",
    "Shared library",
    "System",
]

CATEGORY_COLORS = {
    "Kernel & firmware":       "#b5651d",
    "Boot & init":             "#8a6d3b",
    "Core system":            "#6b7280",
    "Shell & CLI tools":       "#4b5563",
    "Desktop shell":           "#1f6feb",
    "Window/compositor":       "#2563eb",
    "Desktop app":             "#3b82f6",
    "GUI toolkit/framework":   "#0ea5e9",
    "Graphics & display":      "#0891b2",
    "Audio":                   "#7c3aed",
    "Networking":              "#059669",
    "Storage & filesystems":   "#65a30d",
    "Security & crypto":       "#dc2626",
    "Developer tools":         "#d97706",
    "Language runtime":        "#db2777",
    "Multimedia codec/player": "#9333ea",
    "Fonts & icons":           "#a16207",
    "Printing & scanning":     "#0d9488",
    "Bluetooth & devices":     "#0369a1",
    "Virtualization guest":    "#525252",
    "Shared library":          "#94a3b8",
    "System":                  "#78716c",
}

# 1. Curated exact-name roles. These are the packages that define what the OS is;
#    the metadata heuristics below cannot reliably tell (say) a compositor from a
#    plain KDE library, so we name them explicitly.
CURATED = {
    # kernel / firmware
    "linux": "Kernel & firmware", "linux-headers": "Kernel & firmware",
    "linux-firmware": "Kernel & firmware", "linux-firmware-marvell": "Kernel & firmware",
    "amd-ucode": "Kernel & firmware", "intel-ucode": "Kernel & firmware",
    "sof-firmware": "Kernel & firmware", "wireless-regdb": "Kernel & firmware",
    "broadcom-wl": "Kernel & firmware", "b43-fwcutter": "Kernel & firmware",
    # boot / init
    "grub": "Boot & init", "syslinux": "Boot & init", "refind": "Boot & init",
    "efibootmgr": "Boot & init", "edk2-shell": "Boot & init", "os-prober": "Boot & init",
    "memtest86+": "Boot & init", "memtest86+-efi": "Boot & init",
    "mkinitcpio": "Boot & init", "mkinitcpio-archiso": "Boot & init",
    "booster": "Boot & init", "systemd": "Boot & init", "systemd-libs": "Boot & init",
    "plymouth": "Boot & init", "breeze-plymouth": "Boot & init",
    # core system
    "base": "Core system", "base-devel": "Core system", "filesystem": "Core system",
    "glibc": "Core system", "systemd-resolvconf": "Core system",
    "dbus": "Core system", "dbus-broker": "Core system", "polkit": "Core system",
    "sudo": "Core system", "pacman": "Core system", "pambase": "Core system",
    "pam": "Core system", "archlinux-keyring": "Core system",
    # shell & CLI
    "bash": "Shell & CLI tools", "zsh": "Shell & CLI tools",
    "grml-zsh-config": "Shell & CLI tools", "vim": "Shell & CLI tools",
    "nano": "Shell & CLI tools", "less": "Shell & CLI tools", "mc": "Shell & CLI tools",
    "htop": "Shell & CLI tools", "tmux": "Shell & CLI tools", "screen": "Shell & CLI tools",
    "man-db": "Shell & CLI tools", "man-pages": "Shell & CLI tools",
    "rsync": "Shell & CLI tools", "bc": "Shell & CLI tools", "pv": "Shell & CLI tools",
    "diffutils": "Shell & CLI tools", "xdg-utils": "Shell & CLI tools",
    "fastfetch": "Shell & CLI tools", "irssi": "Shell & CLI tools",
    "lynx": "Shell & CLI tools", "jq": "Shell & CLI tools",
    # desktop shell / compositor / login
    "plasma-desktop": "Desktop shell", "plasma-workspace": "Desktop shell",
    "plasma-workspace-wallpapers": "Desktop shell", "systemsettings": "Desktop shell",
    "kscreen": "Desktop shell", "powerdevil": "Desktop shell",
    "kscreenlocker": "Desktop shell", "kactivitymanagerd": "Desktop shell",
    "kglobalacceld": "Desktop shell", "milou": "Desktop shell", "kwrited": "Desktop shell",
    "polkit-kde-agent": "Desktop shell", "plasma-integration": "Desktop shell",
    "kwin": "Window/compositor", "kwin-x11": "Window/compositor",
    "kdecoration": "Window/compositor", "aurorae": "Window/compositor",
    "lightdm": "Desktop shell", "lightdm-gtk-greeter": "Desktop shell",
    "sddm": "Desktop shell", "plasma-login-manager": "Desktop shell",
    "sddm-kcm": "Desktop shell",
    "breeze": "GUI toolkit/framework", "breeze-gtk": "GUI toolkit/framework",
    "oxygen": "GUI toolkit/framework", "oxygen-sounds": "Desktop shell",
    # desktop apps
    "konsole": "Desktop app", "dolphin": "Desktop app", "gwenview": "Desktop app",
    "file_manager": "Desktop app", "xviewer": "Desktop app",
    "tumbler": "Desktop app", "zenity": "Desktop app", "exo": "Desktop app",
    "spectacle": "Desktop app", "kcalc": "Desktop app", "kclock": "Desktop app",
    "kinfocenter": "Desktop app", "plasma-systemmonitor": "Desktop app",
    "discover": "Desktop app", "kamoso": "Desktop app", "gedit": "Desktop app",
    "kdialog": "Desktop app", "gnome-screenshot": "Desktop app",
    "libreoffice-fresh": "Desktop app", "plasma-welcome": "Desktop app",
    "kmenuedit": "Desktop app", "krdp": "Networking",
    "plasma-firewall": "Security & crypto", "plasma-vault": "Security & crypto",
    "plasma-thunderbolt": "Bluetooth & devices", "bluedevil": "Bluetooth & devices",
    "plasma-nm": "Networking", "plasma-pa": "Audio", "print-manager": "Printing & scanning",
    # graphics / display
    "mesa": "Graphics & display", "libglvnd": "Graphics & display",
    "xorg-server": "Graphics & display", "xorg-xwayland": "Graphics & display",
    "xf86-video-vesa": "Graphics & display", "wayland": "Graphics & display",
    "vulkan-icd-loader": "Graphics & display",
    # audio
    "pipewire": "Audio", "pipewire-pulse": "Audio", "pipewire-alsa": "Audio",
    "alsa-utils": "Audio", "alsa-lib": "Audio", "pavucontrol": "Audio",
    "wireplumber": "Audio", "livecd-sounds": "Audio", "ocean-sound-theme": "Audio",
    # networking
    "networkmanager": "Networking", "nm-connection-editor": "Networking",
    "openssh": "Networking", "openvpn": "Networking", "openconnect": "Networking",
    "vpnc": "Networking", "wpa_supplicant": "Networking", "iwd": "Networking",
    "iw": "Networking", "wireless_tools": "Networking", "modemmanager": "Networking",
    "ppp": "Networking", "pptpclient": "Networking", "rp-pppoe": "Networking",
    "xl2tpd": "Networking", "wvdial": "Networking", "bind": "Networking",
    "dnsmasq": "Networking", "tcpdump": "Networking", "nmap": "Networking",
    "ethtool": "Networking", "ndisc6": "Networking", "curl": "Networking",
    "lftp": "Networking", "darkhttpd": "Networking", "cloud-init": "Networking",
    "reflector": "Networking", "avahi": "Networking",
    # storage / filesystems / install
    "archinstall": "Storage & filesystems", "arch-install-scripts": "Storage & filesystems",
    "parted": "Storage & filesystems", "gptfdisk": "Storage & filesystems",
    "cryptsetup": "Security & crypto", "lvm2": "Storage & filesystems",
    "mdadm": "Storage & filesystems", "dmraid": "Storage & filesystems",
    "btrfs-progs": "Storage & filesystems", "xfsprogs": "Storage & filesystems",
    "e2fsprogs": "Storage & filesystems", "f2fs-tools": "Storage & filesystems",
    "exfatprogs": "Storage & filesystems", "ntfs-3g": "Storage & filesystems",
    "dosfstools": "Storage & filesystems", "nilfs-utils": "Storage & filesystems",
    "jfsutils": "Storage & filesystems", "bcachefs-tools": "Storage & filesystems",
    "nfs-utils": "Storage & filesystems", "open-iscsi": "Storage & filesystems",
    "nbd": "Storage & filesystems", "squashfs-tools": "Storage & filesystems",
    "clonezilla": "Storage & filesystems", "partclone": "Storage & filesystems",
    "fsarchiver": "Storage & filesystems", "testdisk": "Storage & filesystems",
    "ddrescue": "Storage & filesystems", "smartmontools": "Storage & filesystems",
    "nvme-cli": "Storage & filesystems", "gpart": "Storage & filesystems",
    "hdparm": "Storage & filesystems", "sdparm": "Storage & filesystems",
    "sg3_utils": "Storage & filesystems", "lsscsi": "Storage & filesystems",
    "mmc-utils": "Storage & filesystems", "udftools": "Storage & filesystems",
    "mtools": "Storage & filesystems", "fatresize": "Storage & filesystems",
    "partimage": "Storage & filesystems", "usbmuxd": "Bluetooth & devices",
    "plasma-disks": "Storage & filesystems", "drbl": "Networking",
    # security & crypto
    "ufw": "Security & crypto", "tpm2-tss": "Security & crypto",
    "tpm2-tools": "Security & crypto", "libfido2": "Security & crypto",
    "pcsclite": "Security & crypto", "sequoia-sq": "Security & crypto",
    "openpgp-card-tools": "Security & crypto", "kwallet-pam": "Security & crypto",
    "gnupg": "Security & crypto", "openssl": "Security & crypto",
    # dev tools / runtimes
    "git": "Developer tools", "neovim": "Developer tools", "gpm": "Developer tools",
    "python": "Language runtime", "python-pip": "Developer tools",
    "go": "Language runtime", "dotnet-sdk": "Developer tools",
    "dotnet-runtime": "Language runtime", "dotnet-host": "Language runtime",
    "tk": "GUI toolkit/framework", "dialog": "Developer tools",
    # multimedia / office
    "vlc": "Multimedia codec/player", "vlc-plugin-ffmpeg": "Multimedia codec/player",
    "vlc-plugin-x264": "Multimedia codec/player", "vlc-plugin-x265": "Multimedia codec/player",
    "vlc-plugin-upnp": "Multimedia codec/player", "ffmpeg": "Multimedia codec/player",
    "libbluray": "Multimedia codec/player", "libdvdnav": "Multimedia codec/player",
    "libdvdread": "Multimedia codec/player", "libdvdcss": "Multimedia codec/player",
    # hardware / peripherals / virt
    "bluez": "Bluetooth & devices", "bluez-utils": "Bluetooth & devices",
    "cups": "Printing & scanning", "usbutils": "Bluetooth & devices",
    "usb_modeswitch": "Bluetooth & devices", "libusb-compat": "Bluetooth & devices",
    "dmidecode": "Bluetooth & devices", "bolt": "Bluetooth & devices",
    "brltty": "Bluetooth & devices", "espeakup": "Bluetooth & devices",
    "wacomtablet": "Bluetooth & devices",
    "open-vm-tools": "Virtualization guest", "qemu-guest-agent": "Virtualization guest",
    "virtualbox-guest-utils-nox": "Virtualization guest", "hyperv": "Virtualization guest",
    # misc/branding
    "xclip": "Shell & CLI tools", "zip": "Shell & CLI tools", "unzip": "Shell & CLI tools",
    "terminus-font": "Fonts & icons", "hicolor-icon-theme": "Fonts & icons",
    "libadwaita": "GUI toolkit/framework", "webp-pixbuf-loader": "Graphics & display",
    # terminfo data files describe terminals; they are CLI plumbing, not graphics
    "foot-terminfo": "Shell & CLI tools", "kitty-terminfo": "Shell & CLI tools",
    "rxvt-unicode-terminfo": "Shell & CLI tools",
    # XML libraries: the libx* name-prefix rule would wrongly call these "graphics"
    "libxml2": "Shared library", "libxslt": "Shared library", "libxmlb": "Shared library",
    # compression libraries: the "ssl" substring in "lossless" would call these crypto
    "brotli": "Shared library", "lzo": "Shared library",
    # non-cryptographic hash: "crypto" substring in "non-cryptographic" would mislabel it
    "xxhash": "Shared library",
}

# 2. Arch group -> role. Applied when a package carries the group and CURATED
#    did not already place it.
GROUP_ROLE = {
    "plasma": "Desktop shell",
    "kf6": "GUI toolkit/framework",
    "kf5": "GUI toolkit/framework",
    "qt6": "GUI toolkit/framework",
    "qt5": "GUI toolkit/framework",
    "kde-applications": "Desktop app",
    "kde-utilities": "Desktop app",
    "kde-graphics": "Desktop app",
    "kde-multimedia": "Multimedia codec/player",
    "kde-network": "Networking",
    "kde-system": "Desktop app",
    "xorg": "Graphics & display",
    "xorg-apps": "Graphics & display",
    "xorg-drivers": "Graphics & display",
    "xorg-fonts": "Fonts & icons",
    "pro-audio": "Audio",
    "vulkan-devel": "Graphics & display",
    "gnome": "Desktop app",
    "sequoia": "Security & crypto",
    "linux-tools": "Developer tools",
    "tree-sitter-grammars": "Developer tools",
}

# 3. Name-pattern rules. (prefix, category) -- matched against the package name.
#    First match wins, so order matters (specific before generic).
NAME_PREFIX_RULES = [
    ("vlc-plugin-", "Multimedia codec/player"),
    ("gst-", "Multimedia codec/player"),
    ("gstreamer", "Multimedia codec/player"),
    ("qt6-", "GUI toolkit/framework"),
    ("qt5-", "GUI toolkit/framework"),
    ("kf6-", "GUI toolkit/framework"),
    ("plasma", "Desktop shell"),
    ("kde", "Desktop app"),
    ("xorg-", "Graphics & display"),
    ("xf86-", "Graphics & display"),
    ("xcb-", "Graphics & display"),
    ("mesa", "Graphics & display"),
    ("vulkan", "Graphics & display"),
    # X11 client libraries only. NOT a bare "libx" -- that also matches libxml2,
    # libxslt, libxmlb (XML libs, curated above) and would mis-tag them "graphics".
    ("libxcb", "Graphics & display"),
    ("libxrandr", "Graphics & display"),
    ("libxrender", "Graphics & display"),
    ("libxfixes", "Graphics & display"),
    ("libxext", "Graphics & display"),
    ("libxi", "Graphics & display"),
    ("libxkb", "Graphics & display"),
    ("libxcursor", "Graphics & display"),
    ("libxdamage", "Graphics & display"),
    ("libxcomposite", "Graphics & display"),
    ("libxinerama", "Graphics & display"),
    ("libxtst", "Graphics & display"),
    ("libxft", "Graphics & display"),
    ("libxaw", "Graphics & display"),
    ("libxmu", "Graphics & display"),
    ("libxpm", "Graphics & display"),
    ("libxss", "Graphics & display"),
    ("libxv", "Graphics & display"),
    ("wayland", "Graphics & display"),
    ("gtk", "GUI toolkit/framework"),
    ("adwaita", "Fonts & icons"),
    ("pipewire", "Audio"),
    ("alsa", "Audio"),
    ("python-", "Developer tools"),
    ("python2-", "Developer tools"),
    ("perl-", "Developer tools"),
    ("dotnet", "Language runtime"),
    ("nodejs", "Language runtime"),
    ("ttf-", "Fonts & icons"),
    ("otf-", "Fonts & icons"),
    ("noto-", "Fonts & icons"),
    ("font", "Fonts & icons"),
    ("tree-sitter", "Developer tools"),
]

NAME_SUBSTR_RULES = [
    ("-icon-theme", "Fonts & icons"),
    ("-cursors", "Fonts & icons"),
    ("-fonts", "Fonts & icons"),
]

# Exact build-toolchain / dev-utility names that would otherwise fall through to
# the generic "System" bucket. These are unambiguous developer tools.
DEV_TOOL_NAMES = {
    "autoconf", "automake", "bison", "flex", "m4", "make", "cmake", "meson",
    "ninja", "pkgconf", "pkg-config", "libtool", "patch", "gettext", "gperf",
    "gcc", "gcc-libs", "binutils", "gdb", "strace", "ltrace", "valgrind",
    "fakeroot", "gc", "guile", "help2man", "texinfo", "which", "groff",
    "sudo-selinux", "swig", "yasm", "nasm", "re2c",
}

# 4. Description keyword rules -- lowercased substring in the DESC field.
#    (keyword, category). Ordered: earlier = higher priority.
DESC_RULES = [
    ("firmware", "Kernel & firmware"),
    ("microcode", "Kernel & firmware"),
    ("bootloader", "Boot & init"),
    ("boot loader", "Boot & init"),
    ("initramfs", "Boot & init"),
    ("filesystem", "Storage & filesystems"),
    ("file system", "Storage & filesystems"),
    ("partition", "Storage & filesystems"),
    ("raid", "Storage & filesystems"),
    ("disk", "Storage & filesystems"),
    ("codec", "Multimedia codec/player"),
    ("decoder", "Multimedia codec/player"),
    ("encoder", "Multimedia codec/player"),
    ("audio", "Audio"),
    ("sound", "Audio"),
    ("bluetooth", "Bluetooth & devices"),
    ("printing", "Printing & scanning"),
    ("printer", "Printing & scanning"),
    ("cups", "Printing & scanning"),
    ("scanner", "Printing & scanning"),
    ("font", "Fonts & icons"),
    ("typeface", "Fonts & icons"),
    ("icon", "Fonts & icons"),
    ("cursor theme", "Fonts & icons"),
    ("dns", "Networking"),
    ("network", "Networking"),
    ("wireless", "Networking"),
    ("vpn", "Networking"),
    ("tls", "Security & crypto"),
    ("ssl", "Security & crypto"),
    ("crypto", "Security & crypto"),
    ("encryption", "Security & crypto"),
    ("password", "Security & crypto"),
    ("keyring", "Security & crypto"),
    ("firewall", "Security & crypto"),
    ("opengl", "Graphics & display"),
    ("vulkan", "Graphics & display"),
    ("x11", "Graphics & display"),
    ("wayland", "Graphics & display"),
    ("graphics", "Graphics & display"),
    ("rendering", "Graphics & display"),
    ("compiler", "Developer tools"),
    ("interpreter", "Language runtime"),
    ("runtime", "Language runtime"),
    ("build", "Developer tools"),
    ("shell", "Shell & CLI tools"),
    ("terminal", "Shell & CLI tools"),
    ("editor", "Developer tools"),
    ("virtual machine", "Virtualization guest"),
    ("hypervisor", "Virtualization guest"),
    ("guest", "Virtualization guest"),
]


# Precompile the DESC keyword rules as WORD-BOUNDARY regexes. Raw substring
# matching produced false positives -- "ssl" in "lossless", "disk" in "diskless",
# "crypto" in "non-cryptographic" -- so every keyword must match as a whole word
# (or hyphenated word). Multi-word keys (e.g. "virtual machine") are matched with
# a flexible separator.
def _compile_desc_rules(rules):
    compiled = []
    for kw, cat in rules:
        parts = [re.escape(w) for w in kw.split()]
        pat = r"\b" + r"[\s-]+".join(parts) + r"\b"
        compiled.append((re.compile(pat), cat))
    return compiled


_DESC_RULES_RX = _compile_desc_rules(DESC_RULES)


def _provides_shared_lib(rec):
    for prov in rec.get("provides_raw", ()):
        base = prov.split("=", 1)[0]
        if ".so" in base:
            return True
    return False


def category_of(pkg, packages):
    """Return the single best human-language category for a package."""
    rec = packages.get(pkg, {})

    # 1. curated exact name
    if pkg in CURATED:
        return CURATED[pkg]

    # 2. Arch group
    for g in rec.get("groups", ()):
        if g in GROUP_ROLE:
            return GROUP_ROLE[g]

    # 2b. exact build-toolchain names
    if pkg in DEV_TOOL_NAMES:
        return "Developer tools"

    # 3. name patterns
    for pre, cat in NAME_PREFIX_RULES:
        if pkg.startswith(pre):
            return cat
    for sub, cat in NAME_SUBSTR_RULES:
        if sub in pkg:
            return cat

    # 4. description keywords (whole-word match; see _compile_desc_rules)
    desc = (rec.get("desc") or "").lower()
    for pat, cat in _DESC_RULES_RX:
        if pat.search(desc):
            return cat

    # 5. fallback: shared library vs generic system component
    if pkg.startswith("lib") or _provides_shared_lib(rec):
        return "Shared library"
    return "System"


def classify(packages, closure, stock_reachable):
    """Return {pkg: {"edition": ..., "category": ..., "azzio_note": str|None}}
    for every package in the closure.

    `stock_reachable` is the set of packages reachable from the stock archiso
    `releng` manifest (from specification_resolve.stock_reachable); it splits the closure
    into the two editions -- see edition_of."""
    out = {}
    for pkg in closure:
        ed = edition_of(pkg, stock_reachable)
        out[pkg] = {
            "edition": ed,
            "category": category_of(pkg, packages),
            "azzio_note": AZZIO_CONFIGURED.get(pkg),
            "removed": pkg in AZZIO_REMOVED,
        }
    return out
