"""
specification_stock_baseline -- the stock archiso `releng` package list, held as a Python
variable so it is not mistaken for an editable manifest.

This is the ground truth for the "Stock Arch" edition in the specification: every package
the official Arch install medium already pulls in. Azzio builds on top of this
list (libraries/packages/packages.x86_64); anything in the final package set that is
NOT reachable from this baseline is an "Azzio Component".

It lives here (a module, not a data file next to packages.x86_64) on purpose:
    * editing it is a deliberate act, not a stray keystroke while browsing the
      real manifest in the editor;
    * it is reference data for the specification tooling, never baked into the ISO, so it
      belongs with the spec_* code that consumes it, not with the ISO's data/.

To refresh after an archiso bump: copy the package names from
    /usr/share/archiso/configs/releng/packages.x86_64
(strip comments/blanks), drop them into STOCK_PACKAGES below, and bump
ARCHISO_VERSION. Order does not matter -- the consumer treats it as a set -- but
it is kept C-locale sorted to diff cleanly against upstream.
"""

# archiso release these package names were captured from, so a future reader can
# tell how stale the baseline is at a glance.
ARCHISO_VERSION = "88-1"

# The upstream archiso `releng` packages.x86_64, verbatim (comments/blank lines
# stripped, C-locale sorted). A tuple, so it reads as fixed reference data.
STOCK_PACKAGES = (
    "alsa-utils",
    "amd-ucode",
    "arch-install-scripts",
    "archinstall",
    "b43-fwcutter",
    "base",
    "bcachefs-tools",
    "bind",
    "bolt",
    "brltty",
    "broadcom-wl",
    "btrfs-progs",
    "clonezilla",
    "cloud-init",
    "cryptsetup",
    "darkhttpd",
    "ddrescue",
    "dhcpcd",
    "diffutils",
    "dmidecode",
    "dmraid",
    "dnsmasq",
    "dosfstools",
    "e2fsprogs",
    "edk2-shell",
    "efibootmgr",
    "espeakup",
    "ethtool",
    "exfatprogs",
    "f2fs-tools",
    "fatresize",
    "foot-terminfo",
    "fsarchiver",
    "gpart",
    "gpm",
    "gptfdisk",
    "grml-zsh-config",
    "grub",
    "hdparm",
    "hyperv",
    "intel-ucode",
    "irssi",
    "iw",
    "iwd",
    "jfsutils",
    "kitty-terminfo",
    "ldns",
    "less",
    "lftp",
    "libfido2",
    "libusb-compat",
    "linux",
    "linux-atm",
    "linux-firmware",
    "linux-firmware-marvell",
    "livecd-sounds",
    "lsscsi",
    "lvm2",
    "lynx",
    "man-db",
    "man-pages",
    "mc",
    "mdadm",
    "memtest86+",
    "memtest86+-efi",
    "mkinitcpio",
    "mkinitcpio-archiso",
    "mkinitcpio-nfs-utils",
    "mmc-utils",
    "modemmanager",
    "mtools",
    "nano",
    "nbd",
    "ndisc6",
    "nfs-utils",
    "nilfs-utils",
    "nmap",
    "ntfs-3g",
    "nvme-cli",
    "open-iscsi",
    "open-vm-tools",
    "openconnect",
    "openpgp-card-tools",
    "openssh",
    "openvpn",
    "partclone",
    "parted",
    "partimage",
    "pcsclite",
    "ppp",
    "pptpclient",
    "pv",
    "qemu-guest-agent",
    "refind",
    "reflector",
    "rsync",
    "rxvt-unicode-terminfo",
    "screen",
    "sdparm",
    "sequoia-sq",
    "sg3_utils",
    "smartmontools",
    "sof-firmware",
    "squashfs-tools",
    "sudo",
    "syslinux",
    "systemd-resolvconf",
    "tcpdump",
    "terminus-font",
    "testdisk",
    "tmux",
    "tpm2-tools",
    "tpm2-tss",
    "udftools",
    "usb_modeswitch",
    "usbmuxd",
    "usbutils",
    "vim",
    "virtualbox-guest-utils-nox",
    "vpnc",
    "wireless-regdb",
    "wireless_tools",
    "wpa_supplicant",
    "wvdial",
    "xdg-utils",
    "xfsprogs",
    "xl2tpd",
    "zsh",
)
