"""Azzio calamares source patch -- add the "Network" installer page (networkq QML module).

The FOURTH Azzio source patch applied to the pinned calamares-3.4.2 tarball in the
recipe's prepare() (see pkgbuild_calamares). Kept in its own module so each patch is a
focused, independently-editable unit; pkgbuild_calamares re-exports the name-constant and
builder below, and pkgbuild.py re-exports them in turn, so callers and recipe_dirs() use
them unchanged.

Unlike the other three patches (which EDIT existing files), this one CREATES a whole new
QML view module under src/modules/networkq/ via `--- /dev/null` / `+++ b/...` hunks. No
top-level CMake edit is needed: src/modules/CMakeLists.txt GLOBS its subdirectories and
calls calamares_add_module_subdirectory() on each, so a new networkq/ directory is picked
up automatically. QML is enabled in the Azzio build (WITH_QML=ON); the module's
CMakeLists guards on WITH_QML and skips cleanly if it were ever off.

WHAT THE PAGE DOES. A "Network" page with an "Automatic (DHCP)" (default) vs "Manual"
radio; when Manual, five text fields -- IPv4 address, subnet mask, default gateway,
DNS 1, DNS 2 -- two-way bound to a C++ Config QObject. On page-leave the view step's
onLeave() calls Config::finalizeGlobalStorage(), which publishes the choice to
GlobalStorage: "networkMethod" always, and (only for manual) "networkIpv4",
"networkSubnetMask", "networkGateway", "networkDns1", "networkDns2". The companion
networkcfg-static patch (a separate module) reads those keys at exec time and writes a
0600 static NetworkManager profile on the installed target. DHCP leaves stock behaviour.

The diff is assembled from a line-by-line list of strings so every unified-diff CONTEXT
line keeps its exact single leading space -- a triple-quoted literal would let an editor
strip trailing spaces and silently break `patch`. A context drift on a version bump makes
`patch` fail LOUDLY in prepare() (the build aborts) rather than silently dropping the
feature; regenerate the hunks via `diff -u /dev/null <file>` against the new source then.
"""

from __future__ import annotations


CALAMARES_NETWORKQ_PATCH_NAME = "azzio-calamares-networkq.patch"


def calamares_networkq_patch() -> str:
    r"""Unified diff (-p1) applied to the extracted calamares-3.4.2 source in the
    recipe's prepare(): CREATE the src/modules/networkq/ QML view module (Config,
    NetworkQmlViewStep, networkq.qml, networkq.qrc, networkq.conf, CMakeLists.txt) that
    adds the "Network" installer page. Each file is a `--- /dev/null` new-file hunk, so
    the patch only ever ADDS files; the module is auto-discovered by the src/modules
    CMake glob. Verified to apply with `patch -p1 --fuzz=0` against the pinned tarball.

    Same authoring rule as the sibling patches: assembled line-by-line so every
    unified-diff line (context, addition, blank context) keeps its exact leading
    character. Regenerate via `diff -u /dev/null <file>` on a version bump.
    """
    lines = [
        "--- /dev/null",
        "+++ b/src/modules/networkq/Config.h",
        "@@ -0,0 +1,79 @@",
        "+/* === This file is part of Calamares - <https://calamares.io> ===",
        "+ *",
        "+ *   SPDX-License-Identifier: GPL-3.0-or-later",
        "+ *",
        "+ *   Azzio: network configuration page (static IPv4 vs DHCP). See networkq.qml.",
        "+ */",
        "+",
        "+#ifndef NETWORKQ_CONFIG_H",
        "+#define NETWORKQ_CONFIG_H",
        "+",
        "+#include \"DllMacro.h\"",
        "+",
        "+#include <QObject>",
        "+#include <QString>",
        "+#include <QVariantMap>",
        "+",
        "+/**",
        "+ * Backing object for the Azzio \"Network\" QML page. Holds the DHCP/manual choice",
        "+ * and, for manual, the five static-IPv4 fields, and publishes them to GlobalStorage",
        "+ * on page-leave so the networkcfg job can write a static NetworkManager profile on",
        "+ * the target. Each field is a two-way QML property (READ/WRITE/NOTIFY).",
        "+ */",
        "+class PLUGINDLLEXPORT Config : public QObject",
        "+{",
        "+    Q_OBJECT",
        "+",
        "+    // \"dhcp\" (default) or \"manual\". Only when \"manual\" are the five fields written.",
        "+    Q_PROPERTY( QString method READ method WRITE setMethod NOTIFY methodChanged FINAL )",
        "+    Q_PROPERTY( QString ipv4 READ ipv4 WRITE setIpv4 NOTIFY ipv4Changed FINAL )",
        "+    Q_PROPERTY( QString subnetMask READ subnetMask WRITE setSubnetMask NOTIFY subnetMaskChanged FINAL )",
        "+    Q_PROPERTY( QString gateway READ gateway WRITE setGateway NOTIFY gatewayChanged FINAL )",
        "+    Q_PROPERTY( QString dns1 READ dns1 WRITE setDns1 NOTIFY dns1Changed FINAL )",
        "+    Q_PROPERTY( QString dns2 READ dns2 WRITE setDns2 NOTIFY dns2Changed FINAL )",
        "+",
        "+public:",
        "+    explicit Config( QObject* parent = nullptr );",
        "+    ~Config() override = default;",
        "+",
        "+    QString method() const { return m_method; }",
        "+    void setMethod( const QString& v );",
        "+",
        "+    QString ipv4() const { return m_ipv4; }",
        "+    void setIpv4( const QString& v );",
        "+",
        "+    QString subnetMask() const { return m_subnetMask; }",
        "+    void setSubnetMask( const QString& v );",
        "+",
        "+    QString gateway() const { return m_gateway; }",
        "+    void setGateway( const QString& v );",
        "+",
        "+    QString dns1() const { return m_dns1; }",
        "+    void setDns1( const QString& v );",
        "+",
        "+    QString dns2() const { return m_dns2; }",
        "+    void setDns2( const QString& v );",
        "+",
        "+    void setConfigurationMap( const QVariantMap& configurationMap );",
        "+",
        "+    /// Publish the current choice to GlobalStorage (called from the view step's onLeave()).",
        "+    void finalizeGlobalStorage() const;",
        "+",
        "+signals:",
        "+    void methodChanged( const QString& );",
        "+    void ipv4Changed( const QString& );",
        "+    void subnetMaskChanged( const QString& );",
        "+    void gatewayChanged( const QString& );",
        "+    void dns1Changed( const QString& );",
        "+    void dns2Changed( const QString& );",
        "+",
        "+private:",
        "+    QString m_method = QStringLiteral( \"dhcp\" );",
        "+    QString m_ipv4;",
        "+    QString m_subnetMask;",
        "+    QString m_gateway;",
        "+    QString m_dns1;",
        "+    QString m_dns2;",
        "+};",
        "+",
        "+#endif  // NETWORKQ_CONFIG_H",
        "--- /dev/null",
        "+++ b/src/modules/networkq/Config.cpp",
        "@@ -0,0 +1,107 @@",
        "+/* === This file is part of Calamares - <https://calamares.io> ===",
        "+ *",
        "+ *   SPDX-License-Identifier: GPL-3.0-or-later",
        "+ *",
        "+ *   Azzio: network configuration page backing object.",
        "+ */",
        "+",
        "+#include \"Config.h\"",
        "+",
        "+#include \"GlobalStorage.h\"",
        "+#include \"JobQueue.h\"",
        "+",
        "+Config::Config( QObject* parent )",
        "+    : QObject( parent )",
        "+{",
        "+}",
        "+",
        "+void",
        "+Config::setMethod( const QString& v )",
        "+{",
        "+    if ( v != m_method )",
        "+    {",
        "+        m_method = v;",
        "+        emit methodChanged( v );",
        "+    }",
        "+}",
        "+",
        "+void",
        "+Config::setIpv4( const QString& v )",
        "+{",
        "+    if ( v != m_ipv4 )",
        "+    {",
        "+        m_ipv4 = v;",
        "+        emit ipv4Changed( v );",
        "+    }",
        "+}",
        "+",
        "+void",
        "+Config::setSubnetMask( const QString& v )",
        "+{",
        "+    if ( v != m_subnetMask )",
        "+    {",
        "+        m_subnetMask = v;",
        "+        emit subnetMaskChanged( v );",
        "+    }",
        "+}",
        "+",
        "+void",
        "+Config::setGateway( const QString& v )",
        "+{",
        "+    if ( v != m_gateway )",
        "+    {",
        "+        m_gateway = v;",
        "+        emit gatewayChanged( v );",
        "+    }",
        "+}",
        "+",
        "+void",
        "+Config::setDns1( const QString& v )",
        "+{",
        "+    if ( v != m_dns1 )",
        "+    {",
        "+        m_dns1 = v;",
        "+        emit dns1Changed( v );",
        "+    }",
        "+}",
        "+",
        "+void",
        "+Config::setDns2( const QString& v )",
        "+{",
        "+    if ( v != m_dns2 )",
        "+    {",
        "+        m_dns2 = v;",
        "+        emit dns2Changed( v );",
        "+    }",
        "+}",
        "+",
        "+void",
        "+Config::setConfigurationMap( const QVariantMap& configurationMap )",
        "+{",
        "+    // No module-level configuration keys are consumed; the page ships no defaults",
        "+    // beyond method=\"dhcp\". Kept for symmetry with the other view-step configs.",
        "+    Q_UNUSED( configurationMap )",
        "+}",
        "+",
        "+void",
        "+Config::finalizeGlobalStorage() const",
        "+{",
        "+    Calamares::GlobalStorage* gs = Calamares::JobQueue::instance()->globalStorage();",
        "+    if ( !gs )",
        "+    {",
        "+        return;",
        "+    }",
        "+",
        "+    // Always publish the method so the networkcfg job knows whether to act. The five",
        "+    // static fields are only meaningful (and only published) for a manual configuration;",
        "+    // an empty IPv4 is treated by the job as \"leave it on DHCP\".",
        "+    gs->insert( QStringLiteral( \"networkMethod\" ), m_method );",
        "+    if ( m_method == QStringLiteral( \"manual\" ) )",
        "+    {",
        "+        gs->insert( QStringLiteral( \"networkIpv4\" ), m_ipv4.trimmed() );",
        "+        gs->insert( QStringLiteral( \"networkSubnetMask\" ), m_subnetMask.trimmed() );",
        "+        gs->insert( QStringLiteral( \"networkGateway\" ), m_gateway.trimmed() );",
        "+        gs->insert( QStringLiteral( \"networkDns1\" ), m_dns1.trimmed() );",
        "+        gs->insert( QStringLiteral( \"networkDns2\" ), m_dns2.trimmed() );",
        "+    }",
        "+}",
        "--- /dev/null",
        "+++ b/src/modules/networkq/NetworkQmlViewStep.h",
        "@@ -0,0 +1,41 @@",
        "+/* === This file is part of Calamares - <https://calamares.io> ===",
        "+ *",
        "+ *   SPDX-License-Identifier: GPL-3.0-or-later",
        "+ *",
        "+ *   Azzio: \"Network\" QML view step (DHCP vs static IPv4). See Config.h / networkq.qml.",
        "+ */",
        "+",
        "+#ifndef NETWORKQMLVIEWSTEP_H",
        "+#define NETWORKQMLVIEWSTEP_H",
        "+",
        "+#include \"Config.h\"",
        "+",
        "+#include \"DllMacro.h\"",
        "+#include \"utils/PluginFactory.h\"",
        "+#include \"viewpages/QmlViewStep.h\"",
        "+",
        "+#include <QObject>",
        "+",
        "+class PLUGINDLLEXPORT NetworkQmlViewStep : public Calamares::QmlViewStep",
        "+{",
        "+    Q_OBJECT",
        "+",
        "+public:",
        "+    explicit NetworkQmlViewStep( QObject* parent = nullptr );",
        "+    ~NetworkQmlViewStep() override;",
        "+",
        "+    QString prettyName() const override;",
        "+",
        "+    void onLeave() override;",
        "+",
        "+    void setConfigurationMap( const QVariantMap& configurationMap ) override;",
        "+",
        "+    QObject* getConfig() override { return m_config; }",
        "+",
        "+private:",
        "+    Config* m_config;",
        "+};",
        "+",
        "+CALAMARES_PLUGIN_FACTORY_DECLARATION( NetworkQmlViewStepFactory )",
        "+",
        "+#endif  // NETWORKQMLVIEWSTEP_H",
        "--- /dev/null",
        "+++ b/src/modules/networkq/NetworkQmlViewStep.cpp",
        "@@ -0,0 +1,43 @@",
        "+/* === This file is part of Calamares - <https://calamares.io> ===",
        "+ *",
        "+ *   SPDX-License-Identifier: GPL-3.0-or-later",
        "+ *",
        "+ *   Azzio: \"Network\" QML view step.",
        "+ */",
        "+",
        "+#include \"NetworkQmlViewStep.h\"",
        "+",
        "+#include \"Config.h\"",
        "+",
        "+#include <QVariant>",
        "+",
        "+NetworkQmlViewStep::NetworkQmlViewStep( QObject* parent )",
        "+    : Calamares::QmlViewStep( parent )",
        "+    , m_config( new Config( this ) )",
        "+{",
        "+}",
        "+",
        "+NetworkQmlViewStep::~NetworkQmlViewStep() {}",
        "+",
        "+QString",
        "+NetworkQmlViewStep::prettyName() const",
        "+{",
        "+    return tr( \"Network\" );",
        "+}",
        "+",
        "+void",
        "+NetworkQmlViewStep::onLeave()",
        "+{",
        "+    // Push the DHCP/manual choice (and, when manual, the static fields) into",
        "+    // GlobalStorage so the networkcfg job can write a static profile on the target.",
        "+    m_config->finalizeGlobalStorage();",
        "+}",
        "+",
        "+void",
        "+NetworkQmlViewStep::setConfigurationMap( const QVariantMap& configurationMap )",
        "+{",
        "+    m_config->setConfigurationMap( configurationMap );",
        "+    Calamares::QmlViewStep::setConfigurationMap( configurationMap );  // call parent implementation last",
        "+}",
        "+",
        "+CALAMARES_PLUGIN_FACTORY_DEFINITION( NetworkQmlViewStepFactory, registerPlugin< NetworkQmlViewStep >(); )",
        "--- /dev/null",
        "+++ b/src/modules/networkq/networkq.qml",
        "@@ -0,0 +1,233 @@",
        "+/* === This file is part of Calamares - <https://calamares.io> ===",
        "+ *",
        "+ *   SPDX-License-Identifier: GPL-3.0-or-later",
        "+ *",
        "+ *   Azzio \"Network\" page: choose Automatic (DHCP) or Manual static IPv4.",
        "+ *   The five manual fields are two-way bound to the C++ Config object exposed",
        "+ *   as `config`; Config.finalizeGlobalStorage() (view step onLeave) hands them",
        "+ *   to the networkcfg job, which writes a static NetworkManager profile on the",
        "+ *   installed target. `config` is the context property set by NetworkQmlViewStep.",
        "+ *",
        "+ *   THEME: the page paints its OWN opaque background (#323232) and light text,",
        "+ *   matching the other installer pages' body colour; without this the view renders",
        "+ *   on a transparent/!default surface, so it was unreadable against the rest of the",
        "+ *   installer. It uses ONLY QtQuick + QtQuick.Controls/Layouts (both shipped on the",
        "+ *   ISO via qt6-declarative) -- NOT org.kde.kirigami, which the Azzio ISO does not",
        "+ *   ship (only the widget `users` module is used, so kirigami was never installed).",
        "+ */",
        "+",
        "+import io.calamares.ui 1.0",
        "+",
        "+import QtQuick",
        "+import QtQuick.Controls",
        "+import QtQuick.Layouts",
        "+",
        "+Item {",
        "+    id: networkPage",
        "+",
        "+    // Fallback intrinsic size only; inside Calamares the view step BINDS width/height",
        "+    // to the embedding window's content item (see QmlViewStep.cpp Qt6 path), so a",
        "+    // hard-coded width/height would just be overwritten. implicitWidth/Height keeps a",
        "+    // sane size when the page is previewed standalone (e.g. qml networkq.qml).",
        "+    implicitWidth: 800",
        "+    implicitHeight: 520",
        "+",
        "+    // Azzio installer theme: the same #323232 body as every other installer page,",
        "+    // white headings, slate body text, blue accent. Fields get a slightly lighter",
        "+    // panel so they are visibly editable on the dark background.",
        "+    readonly property color bgColor:      \"#323232\"",
        "+    readonly property color panelColor:   \"#3c3c3c\"",
        "+    readonly property color headingColor: \"#ffffff\"",
        "+    readonly property color textColor:    \"#cbd5e1\"",
        "+    readonly property color mutedColor:   \"#8a8a8a\"",
        "+    readonly property color accentColor:  \"#3b82f6\"",
        "+",
        "+    // Opaque #323232 page background so the page matches the rest of the installer",
        "+    // and its text is readable (fixes the \"Network section background does not match\"",
        "+    // report). Same colour as every other Calamares page body.",
        "+    Rectangle {",
        "+        anchors.fill: parent",
        "+        color: networkPage.bgColor",
        "+    }",
        "+",
        "+    Flickable {",
        "+        id: flick",
        "+        anchors.fill: parent",
        "+        // contentHeight is the content's REAL bottom edge (y + implicitHeight) plus a",
        "+        // bottom margin -- no phantom padding. contentWidth pinned to the viewport so",
        "+        // it never scrolls sideways. StopAtBounds disables the default overshoot drag,",
        "+        // which let the page be dragged \"a tiny bit\" up/down even when it fully fits.",
        "+        contentWidth: width",
        "+        contentHeight: content.y + content.implicitHeight + 24",
        "+        boundsBehavior: Flickable.StopAtBounds",
        "+        clip: true",
        "+        ScrollBar.vertical: ScrollBar { policy: ScrollBar.AsNeeded }",
        "+",
        "+        ColumnLayout {",
        "+            id: content",
        "+            width: flick.width - 48",
        "+            x: 24",
        "+            y: 24",
        "+            spacing: 18",
        "+",
        "+            Text {",
        "+                text: qsTr(\"Network\")",
        "+                color: networkPage.headingColor",
        "+                font.pointSize: 18",
        "+                font.bold: true",
        "+            }",
        "+",
        "+            ColumnLayout {",
        "+                spacing: 6",
        "+",
        "+                // Use each RadioButton's NATIVE `text` property. With a custom contentItem",
        "+                // and an empty text, the Basic style centres the indicator over the",
        "+                // available width (RadioButton.qml: x is control.text ? leftPadding :",
        "+                // leftPadding + (availableWidth - width)/2), so the circle landed ON TOP",
        "+                // of the label. Native text pins the indicator left with the label beside",
        "+                // it; palette.windowText colours the label and palette.text the dot, so",
        "+                // the dark theme is preserved without fighting the control's own layout.",
        "+                //",
        "+                // ROOT-CAUSE FIX (Manual left every field greyed out): the Config setters",
        "+                // (setMethod/setIpv4/...) are plain Qt property WRITE accessors, NOT",
        "+                // Q_INVOKABLE methods/slots, so they are NOT callable by name from QML.",
        "+                // `config.setMethod(\"manual\")` throws \"Property 'setMethod' ... is not a",
        "+                // function\" and the onClicked handler ABORTS before config.method ever",
        "+                // changes, so isManual stays false and the fields stay disabled forever.",
        "+                // Assign the PROPERTY instead (`config.method = \"manual\"`): that invokes the",
        "+                // very same WRITE setter the supported way and actually flips the method.",
        "+                RadioButton {",
        "+                    id: dhcpRadio",
        "+                    text: qsTr(\"Automatic (DHCP)\")",
        "+                    // config is a context property, momentarily null while the component",
        "+                    // loads asynchronously; `config &&` short-circuits to false during that",
        "+                    // window and the binding re-evaluates once config arrives.",
        "+                    checked: config && config.method === \"dhcp\"",
        "+                    onClicked: if ( config ) config.method = \"dhcp\"",
        "+                    palette.text: networkPage.accentColor",
        "+                    palette.windowText: networkPage.headingColor",
        "+                }",
        "+                RadioButton {",
        "+                    id: manualRadio",
        "+                    text: qsTr(\"Manual\")",
        "+                    checked: config && config.method === \"manual\"",
        "+                    onClicked: if ( config ) config.method = \"manual\"",
        "+                    palette.text: networkPage.accentColor",
        "+                    palette.windowText: networkPage.headingColor",
        "+                }",
        "+            }",
        "+",
        "+            GridLayout {",
        "+                id: manualGrid",
        "+                Layout.fillWidth: true",
        "+                columns: 2",
        "+                columnSpacing: 16",
        "+                rowSpacing: 10",
        "+                // isManual drives BOTH the dim look (opacity, here on the layout) and each",
        "+                // field's `enabled` (set PER-FIELD below, not on this layout). Stock",
        "+                // Calamares always puts `enabled:` on the leaf control (usersq-qt6.qml:",
        "+                // `enabled: config.isEditable(...)` on each TextField) and NEVER on a",
        "+                // QtQuick.Layouts item: on the real Qt6 build a Layout's `enabled` does not",
        "+                // reliably cascade to the children it positions, so gating the GridLayout",
        "+                // left every field greyed even after Manual flipped config.method. Opacity",
        "+                // DOES cascade, so it stays here; `enabled` moves onto the fields.",
        "+                readonly property bool isManual: config ? config.method === \"manual\" : false",
        "+                opacity: isManual ? 1.0 : 0.4",
        "+",
        "+                Label { text: qsTr(\"IPv4 address\"); color: networkPage.textColor }",
        "+                TextField {",
        "+                    id: ipv4Field",
        "+                    Layout.fillWidth: true",
        "+                    enabled: manualGrid.isManual",
        "+                    color: networkPage.headingColor",
        "+                    placeholderTextColor: networkPage.mutedColor",
        "+                    placeholderText: \"192.168.0.100\"",
        "+                    // Null-guarded read; write back on edit (config is non-null by the time",
        "+                    // the user can type, but the read binding evaluates during the load window).",
        "+                    text: config ? config.ipv4 : \"\"",
        "+                    onTextChanged: if ( config ) config.ipv4 = text",
        "+                    background: Rectangle {",
        "+                        radius: 4",
        "+                        color: networkPage.panelColor",
        "+                        border.width: 1",
        "+                        // Reference the field by id, not `parent`: inside an inline background",
        "+                        // delegate `parent` is not reliably the control on Qt6.",
        "+                        border.color: ipv4Field.activeFocus ? networkPage.accentColor : networkPage.mutedColor",
        "+                    }",
        "+                }",
        "+",
        "+                Label { text: qsTr(\"Subnet mask\"); color: networkPage.textColor }",
        "+                TextField {",
        "+                    id: subnetField",
        "+                    Layout.fillWidth: true",
        "+                    enabled: manualGrid.isManual",
        "+                    color: networkPage.headingColor",
        "+                    placeholderTextColor: networkPage.mutedColor",
        "+                    placeholderText: \"255.255.255.0\"",
        "+                    text: config ? config.subnetMask : \"\"",
        "+                    onTextChanged: if ( config ) config.subnetMask = text",
        "+                    background: Rectangle {",
        "+                        radius: 4",
        "+                        color: networkPage.panelColor",
        "+                        border.width: 1",
        "+                        border.color: subnetField.activeFocus ? networkPage.accentColor : networkPage.mutedColor",
        "+                    }",
        "+                }",
        "+",
        "+                Label { text: qsTr(\"Default gateway\"); color: networkPage.textColor }",
        "+                TextField {",
        "+                    id: gatewayField",
        "+                    Layout.fillWidth: true",
        "+                    enabled: manualGrid.isManual",
        "+                    color: networkPage.headingColor",
        "+                    placeholderTextColor: networkPage.mutedColor",
        "+                    placeholderText: \"192.168.0.1\"",
        "+                    text: config ? config.gateway : \"\"",
        "+                    onTextChanged: if ( config ) config.gateway = text",
        "+                    background: Rectangle {",
        "+                        radius: 4",
        "+                        color: networkPage.panelColor",
        "+                        border.width: 1",
        "+                        border.color: gatewayField.activeFocus ? networkPage.accentColor : networkPage.mutedColor",
        "+                    }",
        "+                }",
        "+",
        "+                Label { text: qsTr(\"DNS 1\"); color: networkPage.textColor }",
        "+                TextField {",
        "+                    id: dns1Field",
        "+                    Layout.fillWidth: true",
        "+                    enabled: manualGrid.isManual",
        "+                    color: networkPage.headingColor",
        "+                    placeholderTextColor: networkPage.mutedColor",
        "+                    placeholderText: \"1.1.1.1\"",
        "+                    text: config ? config.dns1 : \"\"",
        "+                    onTextChanged: if ( config ) config.dns1 = text",
        "+                    background: Rectangle {",
        "+                        radius: 4",
        "+                        color: networkPage.panelColor",
        "+                        border.width: 1",
        "+                        border.color: dns1Field.activeFocus ? networkPage.accentColor : networkPage.mutedColor",
        "+                    }",
        "+                }",
        "+",
        "+                Label { text: qsTr(\"DNS 2\"); color: networkPage.textColor }",
        "+                TextField {",
        "+                    id: dns2Field",
        "+                    Layout.fillWidth: true",
        "+                    enabled: manualGrid.isManual",
        "+                    color: networkPage.headingColor",
        "+                    placeholderTextColor: networkPage.mutedColor",
        "+                    placeholderText: \"8.8.8.8\"",
        "+                    text: config ? config.dns2 : \"\"",
        "+                    onTextChanged: if ( config ) config.dns2 = text",
        "+                    background: Rectangle {",
        "+                        radius: 4",
        "+                        color: networkPage.panelColor",
        "+                        border.width: 1",
        "+                        border.color: dns2Field.activeFocus ? networkPage.accentColor : networkPage.mutedColor",
        "+                    }",
        "+                }",
        "+            }",
        "+        }",
        "+    }",
        "+}",
        "--- /dev/null",
        "+++ b/src/modules/networkq/networkq.qrc",
        "@@ -0,0 +1,5 @@",
        "+<!DOCTYPE RCC><RCC version=\"1.0\">",
        "+<qresource>",
        "+  <file alias=\"networkq.qml\">networkq.qml</file>",
        "+</qresource>",
        "+</RCC>",
        "--- /dev/null",
        "+++ b/src/modules/networkq/networkq.conf",
        "@@ -0,0 +1,15 @@",
        "+# SPDX-License-Identifier: CC0-1.0",
        "+#",
        "+# Azzio \"Network\" QML page (Automatic/DHCP vs Manual static IPv4). The page has no",
        "+# tunable behaviour of its own; the only configurable thing is the sidebar/progress",
        "+# label, kept here so it stays translatable like the other QML modules.",
        "+---",
        "+# Load the QML from the module's compiled-in resources (qrc), matching notesqml/usersq.",
        "+qmlSearch: both",
        "+",
        "+# The QML file basename (networkq.qml) inside the qrc.",
        "+qmlFilename: networkq",
        "+",
        "+# Name shown in the installer sidebar / progress tree.",
        "+qmlLabel:",
        "+    network: \"Network\"",
        "--- /dev/null",
        "+++ b/src/modules/networkq/CMakeLists.txt",
        "@@ -0,0 +1,21 @@",
        "+# === This file is part of Calamares - <https://calamares.io> ===",
        "+#",
        "+#   SPDX-License-Identifier: BSD-2-Clause",
        "+#",
        "+# Azzio: \"Network\" QML view module (static IPv4 vs DHCP). Auto-discovered by the",
        "+# src/modules glob, so no top-level CMake edit is needed.",
        "+if(NOT WITH_QML)",
        "+    calamares_skip_module( \"networkq (QML is not supported in this build)\" )",
        "+    return()",
        "+endif()",
        "+",
        "+calamares_add_plugin(networkq",
        "+    TYPE viewmodule",
        "+    EXPORT_MACRO PLUGINDLLEXPORT_PRO",
        "+    SOURCES",
        "+        NetworkQmlViewStep.cpp",
        "+        Config.cpp",
        "+    RESOURCES",
        "+        networkq.qrc",
        "+    SHARED_LIB",
        "+)"
    ]
    # Trailing newline so the last line is terminated (patch/POSIX text file).
    return "\n".join(lines) + "\n"
