"""Azzio calamares source patch -- hide Back + Next on the Finish page.

One of the three Azzio source patches applied to the pinned calamares-3.4.2 tarball
in the recipe's prepare() (see pkgbuild_calamares). Kept in its own module so each
patch is a focused, independently-editable unit; pkgbuild_calamares re-exports the
name-constant and builder below, and pkgbuild.py re-exports them in turn, so callers
and recipe_dirs() use them unchanged.

The diff is assembled from a line-by-line list of strings so every unified-diff CONTEXT
line keeps its exact single leading space -- a triple-quoted literal would let an editor
strip trailing spaces and silently break `patch`. A context drift on a version bump
makes `patch` fail LOUDLY in prepare() (the build aborts) rather than silently dropping
the customization; regenerate the hunks via `diff -u` against the new source then.
"""

from __future__ import annotations


# ---------------------------------------------------------------------------
# calamares -- source patch: hide Back + Next on the Finish page AND during Install
# ---------------------------------------------------------------------------
# The installer's Back/Next buttons are the MAIN-WINDOW navigation buttons driven by
# libcalamaresui's ViewManager, not anything a module .conf can reach -- so removing
# them can only be done in C++. Both the finished ViewStep and the running install
# (ExecutionViewStep) ALREADY return false from isBackEnabled()/isNextEnabled(), but
# that only DISABLES (greys) the buttons; they stay visible. To HIDE them, this patch
# adds two calls in ViewManager::updateButtonLabels(), each calling
# updateBackAndNextVisibility(false) -- which fires backAndNextVisibleChanged(false),
# wired in CalamaresWindow to setVisible(false) on BOTH buttons:
#
#   1. FINISH page -- inside the existing `isAtVeryEnd()` branch (taken only on the last
#      step, the finished page -- it returns isAtEnd()==true). Only the "Done" (quit)
#      button, kept visible in that same branch, remains.
#   2. INSTALL (exec) step -- inside the `else` branch, gated on
#      stepIsExecute(m_currentStep) so ONLY the running install step hides them; the
#      ordinary UI steps (welcome/locale/keyboard/partition/users/summary) keep their
#      normal Back/Next. (PROMPT.md: the Install section's Back/Next are greyed out
#      anyway, so remove them.)
#
# updateButtonLabels() runs LAST in next() (after next()'s own updateBackAndNextVisibility()
# call), so both calls WIN for their step; every other non-final UI step falls through the
# else branch's stepIsExecute() guard and keeps its normal button visibility.
#
# Kept in its OWN patch (not folded into azzio-calamares-defaults.patch) so the two
# concerns stay independent -- defaults is the Users/Keyboard UI, this is a libcalamaresui
# navigation tweak. Same fail-loud-on-drift contract: the pinned tarball guarantees the
# context; a version bump that moves these lines makes `patch` abort the build.
CALAMARES_FINISH_BUTTONS_PATCH_NAME = "azzio-calamares-finish-buttons.patch"


def calamares_finish_buttons_patch() -> str:
    r"""Unified diff (-p1) applied to the extracted calamares-3.4.2 source in the
    recipe's prepare(), after the other two calamares patches: hide the Back and Next
    navigation buttons BOTH on the Finish page AND while the install (exec) step runs
    (see the block comment above). Touches only src/libcalamaresui/ViewManager.cpp.

    Same authoring rule as the sibling patches: assembled line-by-line so every
    unified-diff CONTEXT line keeps its exact single leading space (blank context lines
    are one space) -- a triple-quoted literal would let an editor strip that trailing
    space and silently break `patch`. The two hunk headers (@@ -437,6 ... for the Finish
    branch and @@ -458,4 ... for the exec-step else branch; the latter's NEW-side start
    465 already accounts for the +7 lines the first hunk inserts) were generated by
    `diff -u` against the pinned 3.4.2 source and verified to apply with `patch -p1`;
    regenerate them the same way on a version bump."""
    lines = [
        "--- a/src/libcalamaresui/ViewManager.cpp",
        "+++ b/src/libcalamaresui/ViewManager.cpp",
        "@@ -437,6 +437,13 @@",
        "         UPDATE_BUTTON_PROPERTY( quitVisible, true );",
        '         UPDATE_BUTTON_PROPERTY( quitIcon, "dialog-ok-apply" );',
        "         updateCancelEnabled( true );",
        "+        // Azzio: on the very last step (the Finish page) hide BOTH the Back and Next",
        "+        // buttons -- the install is complete, there is nowhere to go back to and nothing",
        '+        // to advance to; only the "Done" (quit) button, kept visible just above, remains.',
        "+        // This runs after next()'s own updateBackAndNextVisibility() call (updateButtonLabels",
        "+        // is invoked last), so it wins for the finished step. The else branch below hides",
        "+        // them on the running install (exec) step too.",
        "+        updateBackAndNextVisibility( false );",
        "         if ( settings->quitAtEnd() )",
        "         {",
        "             quit();",
        # Second hunk: the else branch (every non-final step). Hide Back+Next while
        # the INSTALL (exec) step is running -- upstream leaves them visible-but-greyed
        # (ExecutionViewStep::isBackEnabled()/isNextEnabled() return false). PROMPT.md:
        # remove them during the Install section since they are greyed out anyway. Gated
        # on stepIsExecute(m_currentStep) so ONLY the exec step hides them; ordinary UI
        # steps (welcome/locale/.../summary) keep normal Back/Next. This runs LAST in
        # next() (updateButtonLabels is invoked last), so it wins over next()'s own
        # updateBackAndNextVisibility(true) for the exec step. NEW-side start is 465 =
        # 458 + 7 (the +7 net lines the finish hunk above inserts). old=4 (2 ctx + blank
        # ctx + quitLabel ctx), new=13 (those 4 ctx + 9 added lines).
        "@@ -458,4 +465,13 @@",
        "         updateCancelEnabled( !settings->disableCancel()",
        "                              && !( stepIsExecute( m_steps, m_currentStep ) && settings->disableCancelDuringExec() ) );",
        "+",
        "+        // Azzio: hide Back+Next while the install (exec) step is running -- they are",
        "+        // disabled (greyed) there anyway (ExecutionViewStep returns false for both), so",
        "+        // PROMPT.md asks for them gone. Only the exec step matches; other UI steps keep",
        "+        // their normal navigation buttons.",
        "+        if ( stepIsExecute( m_steps, m_currentStep ) )",
        "+        {",
        "+            updateBackAndNextVisibility( false );",
        "+        }",
        " ",
        '         UPDATE_BUTTON_PROPERTY( quitLabel, tr( "&Cancel", "@button" ) );',
    ]
    # Trailing newline so the last line is terminated (patch/POSIX text file).
    return "\n".join(lines) + "\n"
