"""xviewer icon override (PROMPT task 5) -- replace the off-putting "spying eye" icon.

xviewer (the GTK image viewer, the Azzio "Photos" default -- image/* maps to it in
packages/azzio/default_applications.py) ships with a default icon that reads like a staring
eye ("it looks like it's spying, genuinely off-putting"). Azzio replaces it with a clean
custom icon -- a framed picture of a sun over mountains in the Azzio blue-gradient-on-dark
badge (assets/icons/xviewer.svg, the same visual identity as the kitty/file_manager/installer icons).

HOW (the kitty/file_manager icon pattern). The SVG asset is the single source of truth. We ship it
to the hicolor SCALABLE apps dir under OUR OWN icon name (XVIEWER_ICON_NAME = azzio-xviewer)
and rasterize it to the standard PNG sizes there, then OVERRIDE xviewer.desktop's Icon= to
that name. Using a NEW icon name (not overwriting the package's `xviewer` icon files) means an
xviewer package upgrade that reships its own icons cannot revert ours -- our name is ours
alone (the same reasoning packages/file_manager uses for azzio-file-manager).

WHAT LANDS WHERE:
  * the custom icon (scalable SVG + PNG rasterizations) under /usr/share/icons/hicolor/... --
    NOT package-owned (new name), so it goes in the airootfs overlay directly (owner "root").
  * xviewer.desktop -- a PACKAGE-OWNED path (xviewer), so like gedit's .desktop it is
    NoExtract'd (pacman.ISO_APP_OVERRIDES) and planted post-pacstrap; the emit_plan entry's
    dest matches an ISO_APP_OVERRIDES target so compiler._emit_apps stages the body.

The .desktop override keeps xviewer's stock Name/Exec/MimeType/Categories (VERIFIED against the
installed xviewer.desktop) and only changes Icon= to the custom icon. compiler._emit_apps
consumes this module's emit_plan() exactly like kitty's (builder/dest/mode/owner + asset/render).
"""

from __future__ import annotations

# --- The .desktop override ------------------------------------------------------
# Package-owned path (xviewer), so this dest is also in pacman.ISO_APP_OVERRIDES and
# NoExtract'd; compiler._emit_apps stages the body for the post-pacstrap install hook.
XVIEWER_DESKTOP_PATH = "/usr/share/applications/xviewer.desktop"

# --- The custom icon ------------------------------------------------------------
# The single-source-of-truth SVG asset and OUR icon name (new, so an xviewer upgrade cannot
# revert it). The .desktop Icon= points at this name.
ICON_ASSET = "icons/xviewer.svg"
XVIEWER_ICON_NAME = "azzio-xviewer"
ICON_SCALABLE_PATH = f"/usr/share/icons/hicolor/scalable/apps/{XVIEWER_ICON_NAME}.svg"
ICON_PNG_SIZES = (16, 22, 24, 32, 48, 64, 128, 256)
ICON_PNG_DIR = "/usr/share/icons/hicolor/{size}x{size}/apps"

_CONF = 0o644


def xviewer_desktop() -> str:
    """/usr/share/applications/xviewer.desktop -- the stock launcher with Icon= pointed at the
    custom Azzio "Photos" icon.

    Name/Exec/MimeType/Categories/StartupNotify are kept as the xviewer package ships them
    (VERIFIED against the installed file); only Icon changes to XVIEWER_ICON_NAME. The full
    MimeType list is preserved so xviewer stays the handler for every image type (it is the
    Photos default). Translations are dropped (the stock file carries hundreds of Name[xx]
    lines; the untranslated Name is enough and keeps this override readable)."""
    return f"""\
[Desktop Entry]
# Azzio xviewer override. Generated by packages/xviewer (edit the Python, not this
# file). Only Icon changes -- to the custom Azzio "Photos" icon ({XVIEWER_ICON_NAME}),
# replacing the off-putting default eye icon. Everything else is stock xviewer.desktop.
Name=Image Viewer
Comment=Browse and rotate images
TryExec=xviewer
Exec=xviewer %U
Icon={XVIEWER_ICON_NAME}
StartupNotify=true
Terminal=false
Type=Application
Categories=GNOME;GTK;Utility;Viewer;
MimeType=image/bmp;image/gif;image/jpeg;image/jpg;image/pjpeg;image/png;image/tiff;image/x-bmp;image/x-gray;image/x-icb;image/x-ico;image/x-png;image/x-portable-anymap;image/x-portable-bitmap;image/x-portable-graymap;image/x-portable-pixmap;image/x-xbitmap;image/x-xpixmap;image/x-pcx;image/svg+xml;image/svg+xml-compressed;image/vnd.wap.wbmp;image/webp;image/heif;image/avif;
Keywords=Picture;Slideshow;Graphics;
"""


def emit_plan() -> list[dict]:
    """Return the emit plan for the xviewer icon override: the scalable SVG master (our asset,
    our icon name), PNG rasterizations at the standard sizes, and the xviewer.desktop override
    (Icon= pointed at the custom icon). Shape matches kitty.emit_plan() (builder/dest/mode/owner
    + asset/render); the .desktop dest matches an ISO_APP_OVERRIDES target so it is staged for
    the post-pacstrap install hook. Returns FRESH dicts so a caller cannot mutate module state."""
    plan: list[dict] = [
        {   # the scalable SVG master (our asset, our icon name).
            "builder": None,
            "asset": ICON_ASSET,
            "dest": ICON_SCALABLE_PATH,
            "mode": _CONF,
            "owner": "root",
        },
        {   # the xviewer.desktop override (package-owned dest -> staged post-pacstrap).
            "builder": xviewer_desktop,
            "dest": XVIEWER_DESKTOP_PATH,
            "mode": _CONF,
            "owner": "root",
        },
    ]
    # PNG rasterizations of the icon at the standard sizes.
    for size in ICON_PNG_SIZES:
        png_dir = ICON_PNG_DIR.format(size=size)
        plan.append({
            "builder": None,
            "render": {"asset": ICON_ASSET, "size": size},
            "dest": f"{png_dir}/{XVIEWER_ICON_NAME}.png",
            "mode": _CONF,
            "owner": "root",
        })
    return plan
