#!/usr/bin/env python3
"""azzio guest command line interface -- the country -> (locale, layout, keymap, english) table.

Kept in its OWN module so the AZZIO_CC markers bracket nothing but the generated
literal: packages.openbox.azzio_command_line_interface() REGENERATES everything between the two markers from
packages/calamares/locale.RESOLVER_COUNTRY_TABLE (the single source of truth) at build time,
so this literal stays in lock-step. The on-disk copy below is a working snapshot so the
package is runnable/importable on its own.
"""

from __future__ import annotations

# BUNDLE_START

# CC -> (locale, xkb_layout, vconsole_keymap, english). `english` 1 means the
# country is English-speaking -> English ONLY (no second layout/locale).
# AZZIO_CC_TABLE_START
COUNTRY_TABLE: dict[str, tuple[str, str, str, int]] = {
    'US': ('en_US.UTF-8', 'us', 'us', 1),
    'GB': ('en_GB.UTF-8', 'us', 'us', 1),
    'AU': ('en_AU.UTF-8', 'us', 'us', 1),
    'NZ': ('en_NZ.UTF-8', 'us', 'us', 1),
    'IE': ('en_IE.UTF-8', 'us', 'us', 1),
    'ZA': ('en_ZA.UTF-8', 'us', 'us', 1),
    'CA': ('en_CA.UTF-8', 'us', 'us', 1),
    'SV': ('es_SV.UTF-8', 'latam', 'la-latin1', 0),
    'MX': ('es_MX.UTF-8', 'latam', 'la-latin1', 0),
    'AR': ('es_AR.UTF-8', 'latam', 'la-latin1', 0),
    'CO': ('es_CO.UTF-8', 'latam', 'la-latin1', 0),
    'CL': ('es_CL.UTF-8', 'latam', 'la-latin1', 0),
    'PE': ('es_PE.UTF-8', 'latam', 'la-latin1', 0),
    'VE': ('es_VE.UTF-8', 'latam', 'la-latin1', 0),
    'EC': ('es_EC.UTF-8', 'latam', 'la-latin1', 0),
    'GT': ('es_GT.UTF-8', 'latam', 'la-latin1', 0),
    'BO': ('es_BO.UTF-8', 'latam', 'la-latin1', 0),
    'CR': ('es_CR.UTF-8', 'latam', 'la-latin1', 0),
    'PY': ('es_PY.UTF-8', 'latam', 'la-latin1', 0),
    'PA': ('es_PA.UTF-8', 'latam', 'la-latin1', 0),
    'UY': ('es_UY.UTF-8', 'latam', 'la-latin1', 0),
    'HN': ('es_HN.UTF-8', 'latam', 'la-latin1', 0),
    'NI': ('es_NI.UTF-8', 'latam', 'la-latin1', 0),
    'DO': ('es_DO.UTF-8', 'latam', 'la-latin1', 0),
    'CU': ('es_CU.UTF-8', 'latam', 'la-latin1', 0),
    'ES': ('es_ES.UTF-8', 'es', 'es', 0),
    'FR': ('fr_FR.UTF-8', 'fr', 'fr', 0),
    'DE': ('de_DE.UTF-8', 'de', 'de', 0),
    'AT': ('de_AT.UTF-8', 'de', 'de', 0),
    'CH': ('de_CH.UTF-8', 'ch', 'de_CH-latin1', 0),
    'IT': ('it_IT.UTF-8', 'it', 'it', 0),
    'PT': ('pt_PT.UTF-8', 'pt', 'pt-latin1', 0),
    'BR': ('pt_BR.UTF-8', 'br', 'br-abnt2', 0),
    'NL': ('nl_NL.UTF-8', 'nl', 'nl', 0),
    'PL': ('pl_PL.UTF-8', 'pl', 'pl', 0),
    'SE': ('sv_SE.UTF-8', 'se', 'sv-latin1', 0),
    'NO': ('nb_NO.UTF-8', 'no', 'no-latin1', 0),
    'DK': ('da_DK.UTF-8', 'dk', 'dk-latin1', 0),
    'FI': ('fi_FI.UTF-8', 'fi', 'fi', 0),
    'CZ': ('cs_CZ.UTF-8', 'cz', 'cz-lat2', 0),
    'HU': ('hu_HU.UTF-8', 'hu', 'hu', 0),
    'TR': ('tr_TR.UTF-8', 'tr', 'trq', 0),
    'RO': ('ro_RO.UTF-8', 'ro', 'ro', 0),
    'HR': ('hr_HR.UTF-8', 'hr', 'croat', 0),
    'SK': ('sk_SK.UTF-8', 'sk', 'sk-qwerty', 0),
    'SI': ('sl_SI.UTF-8', 'si', 'slovene', 0),
    'EE': ('et_EE.UTF-8', 'ee', 'et', 0),
    'LV': ('lv_LV.UTF-8', 'lv', 'lv', 0),
    'LT': ('lt_LT.UTF-8', 'lt', 'lt', 0),
    'IS': ('is_IS.UTF-8', 'is', 'is-latin1', 0),
    'VN': ('vi_VN.UTF-8', 'vn', 'us', 0),
    'IL': ('he_IL.UTF-8', 'il', 'il', 0),
    'RU': ('ru_RU.UTF-8', 'ru', 'ruwin_alt_sh-UTF-8', 0),
    'UA': ('uk_UA.UTF-8', 'ua', 'ua-utf', 0),
    'BY': ('be_BY.UTF-8', 'by', 'by', 0),
    'BG': ('bg_BG.UTF-8', 'bg', 'bg_bds-utf8', 0),
    'RS': ('sr_RS.UTF-8', 'rs', 'sr-cy', 0),
    'MK': ('mk_MK.UTF-8', 'mk', 'mk-utf', 0),
    'GR': ('el_GR.UTF-8', 'gr', 'gr', 0),
    'GE': ('ka_GE.UTF-8', 'ge', 'ge', 0),
    'AM': ('hy_AM.UTF-8', 'am', 'us', 0),
    'IR': ('fa_IR.UTF-8', 'ir', 'us', 0),
    'PK': ('ur_PK.UTF-8', 'pk', 'us', 0),
    'IN': ('hi_IN.UTF-8', 'in', 'us', 0),
    'TH': ('th_TH.UTF-8', 'th', 'us', 0),
    'KH': ('km_KH.UTF-8', 'kh', 'us', 0),
    'LA': ('lo_LA.UTF-8', 'la', 'us', 0),
    'MM': ('my_MM.UTF-8', 'mm', 'us', 0),
    'LK': ('si_LK.UTF-8', 'lk', 'us', 0),
    'JP': ('ja_JP.UTF-8', 'jp', 'jp106', 0),
    'KR': ('ko_KR.UTF-8', 'kr', 'us', 0),
    'CN': ('zh_CN.UTF-8', 'cn', 'us', 0),
    'TW': ('zh_TW.UTF-8', 'tw', 'us', 0),
    'MN': ('mn_MN.UTF-8', 'mn', 'us', 0),
    'SA': ('ar_SA.UTF-8', 'ara', 'us', 0),
    'AE': ('ar_AE.UTF-8', 'ara', 'us', 0),
    'EG': ('ar_EG.UTF-8', 'ara', 'us', 0),
    'IQ': ('ar_IQ.UTF-8', 'ara', 'us', 0),
    'JO': ('ar_JO.UTF-8', 'ara', 'us', 0),
    'KW': ('ar_KW.UTF-8', 'ara', 'us', 0),
    'LB': ('ar_LB.UTF-8', 'ara', 'us', 0),
    'LY': ('ar_LY.UTF-8', 'ara', 'us', 0),
    'OM': ('ar_OM.UTF-8', 'ara', 'us', 0),
    'QA': ('ar_QA.UTF-8', 'ara', 'us', 0),
    'SY': ('ar_SY.UTF-8', 'ara', 'us', 0),
    'YE': ('ar_YE.UTF-8', 'ara', 'us', 0),
    'BH': ('ar_BH.UTF-8', 'ara', 'us', 0),
    'DZ': ('ar_DZ.UTF-8', 'ara', 'us', 0),
    'MA': ('ar_MA.UTF-8', 'ara', 'us', 0),
    'TN': ('ar_TN.UTF-8', 'ara', 'us', 0),
    'SD': ('ar_SD.UTF-8', 'ara', 'us', 0),
}
# AZZIO_CC_TABLE_END
