#!/usr/bin/env python3
"""azzio guest command line interface -- `azzio display` (the Display screen's command surface).

Feature-parity with cinnamon-settings-display for this X11/OpenBox setup, driven by xrandr, PLUS
the GLOBAL SCALE (the single source of truth for UI scaling). What it exposes (each also a row/
screen in the TUI's Display screen):

  azzio display info                     print the xrandr state (outputs, modes, primary)
  azzio display scale [get|<factor>]     get / set the GLOBAL UI SCALE (rewrites ~/.Xresources
                                          Xft.dpi + Xcursor.size and re-applies live via xrdb;
                                          new processes inherit it, and the X DPI updates now)
  azzio display resolution <WxH> [out]   set an output's resolution (xrandr --mode)
  azzio display refresh <rate> [out]     set the refresh rate (xrandr --rate)
  azzio display rotate <normal|left|right|inverted> [out]   rotate/orient an output
  azzio display primary <out>            make an output the primary monitor
  azzio display on <out> / off <out>     enable / disable an output
  azzio display mirror on|off            mirror all outputs onto the primary (on) / extend (off)
  azzio display position <out> <left-of|right-of|above|below> <other>   arrange two monitors

DEFAULT OUTPUT. Where an output is omitted, the connected PRIMARY (or the first connected
output) is used -- so on a single-head VM the commands "just work" without naming the output.

THE GLOBAL SCALE is the important, always-applicable one (a headless/single-head VM still has a
UI scale). It rewrites the SINGLE source's downstream file (~/.Xresources, whose Xft.dpi/
Xcursor.size are derived from packages/openbox/scale) and re-runs `xrdb -merge` so the X DPI changes
for the session; already-running apps that read the DPI at startup pick it up on their next
launch, and the file manager (em-relative) + any DPI-aware app scale immediately. The scale VALUES and the
DPI math live in packages/openbox/scale (mirrored here for the standalone bundle, pinned by a test).

No sudo -- xrandr and the X resource DB are per-session/per-user. Standard library only (bundled
into /usr/local/bin/azzio; see common.py).
"""

from __future__ import annotations

# BUNDLE_START

# The scale choices + DPI math, MIRRORED from packages/openbox/scale (the bundle is standalone; a
# test pins these equal to that single source). Xft.dpi = round(96*scale), Xcursor.size =
# round(24*scale), gtk-xft-dpi (informational) = Xft.dpi*1024.
DISPLAY_SCALE_OPTIONS: tuple[float, ...] = (1.00, 1.25, 1.35, 1.50, 1.75, 2.00)
DISPLAY_SCALE_DEFAULT = 1.35
_BASE_DPI = 96
_BASE_CURSOR = 24
XRESOURCES_FILE = ".Xresources"     # under $HOME


def _disp_xft_dpi(scale: float) -> int:
    return round(_BASE_DPI * scale)


def _disp_cursor(scale: float) -> int:
    return round(_BASE_CURSOR * scale)


def _xresources_path() -> str:
    return os.path.join(os.path.expanduser("~"), XRESOURCES_FILE)


def _xresources_body(scale: float) -> str:
    """The ~/.Xresources content for a scale (same shape packages/openbox.xresources ships)."""
    return (
        "! Azzio X resources. Generated by packages/openbox (edit the Python, not this\n"
        "! file). Xft.dpi is the GLOBAL SCALE backbone (round(96*scale)) every X client reads;\n"
        "! Xcursor.size scales the cursor with it. `azzio display scale` rewrites these.\n"
        f"Xft.dpi: {_disp_xft_dpi(scale)}\n"
        f"Xcursor.size: {_disp_cursor(scale)}\n"
    )


def _current_scale() -> float:
    """The current GLOBAL SCALE, read back from ~/.Xresources' Xft.dpi (scale = dpi/96), or the
    live X resource DB, falling back to the Azzio default. Rounded to 2 dp."""
    dpi = None
    # Prefer the file (authoritative for the next login); fall back to the live xrdb value.
    try:
        for line in open(_xresources_path(), encoding="utf-8"):
            s = line.strip()
            if s.lower().startswith("xft.dpi:"):
                dpi = float(s.split(":", 1)[1].strip())
                break
    except OSError:
        pass
    if dpi is None and _have("xrdb"):
        r = subprocess.run(["xrdb", "-query"], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
        for line in r.stdout.decode("utf-8", "replace").splitlines():
            if line.lower().startswith("xft.dpi:"):
                try:
                    dpi = float(line.split(":", 1)[1].strip())
                except ValueError:
                    pass
                break
    if dpi is None:
        return DISPLAY_SCALE_DEFAULT
    return round(dpi / _BASE_DPI, 2)


def _apply_scale_live(scale: float) -> None:
    """Re-load the rewritten ~/.Xresources into the running X server so the DPI changes now.
    xrdb -merge updates the X resource DB every new client reads. (Already-running apps that
    cached the DPI at startup pick it up on their next launch.)"""
    if os.environ.get("DISPLAY") and _have("xrdb"):
        subprocess.run(["xrdb", "-merge", _xresources_path()],
                       stderr=subprocess.DEVNULL, check=False)


def _scale_status() -> int:
    scale = _current_scale()
    print(f"Global scale: {scale:g}")
    print(f"  Xft.dpi: {_disp_xft_dpi(scale)}  (round(96*scale))")
    print(f"  Xcursor.size: {_disp_cursor(scale)}")
    return 0


def _set_scale(arg: str) -> int:
    """Set the GLOBAL SCALE: rewrite ~/.Xresources (Xft.dpi + Xcursor.size) and re-apply live."""
    try:
        scale = round(float(arg), 2)
    except ValueError:
        _err(f"azzio display scale: not a number: {arg}")
        return 2
    if scale < 0.5 or scale > 4.0:
        _err("azzio display scale: out of range (0.5 .. 4.0)")
        return 2
    path = _xresources_path()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(_xresources_body(scale))
    _apply_scale_live(scale)
    print(f"Global scale set to {scale:g} (Xft.dpi {_disp_xft_dpi(scale)}). "
          "New windows use it now; a re-login applies it everywhere.")
    return 0


def cmd_scale(args: list[str]) -> int:
    """`azzio display scale [get|<factor>]`."""
    if not args or args[0] in ("get", "status"):
        return _scale_status()
    return _set_scale(args[0])


# --- xrandr helpers ---------------------------------------------------------
def _xrandr_query() -> str:
    if not _have("xrandr"):
        return ""
    r = subprocess.run(["xrandr", "--query"], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    return r.stdout.decode("utf-8", "replace")


def _connected_outputs() -> list[str]:
    """Connected output names in xrandr order (e.g. ['HDMI-0', 'eDP-1'])."""
    outs: list[str] = []
    for line in _xrandr_query().splitlines():
        # a line like "HDMI-0 connected primary 1920x1080+0+0 ..." (not indented -> an output)
        if line and not line[0].isspace() and " connected" in line:
            outs.append(line.split()[0])
    return outs


def _primary_output() -> str:
    """The primary output (the one marked 'primary'), else the first connected, else ''."""
    for line in _xrandr_query().splitlines():
        if line and not line[0].isspace() and " connected" in line and " primary " in f" {line} ":
            return line.split()[0]
    outs = _connected_outputs()
    return outs[0] if outs else ""


def _resolve_output(args: list[str], idx: int) -> str:
    """The output named at args[idx] if present, else the default (primary/first)."""
    if len(args) > idx and args[idx]:
        return args[idx]
    return _primary_output()


def _run_xrandr(*xargs: str) -> int:
    if not _have("xrandr"):
        _err("azzio display: xrandr not found")
        return 1
    return subprocess.run(["xrandr", *xargs]).returncode


def _display_info() -> int:
    out = _xrandr_query()
    if not out:
        print("xrandr unavailable (no X display or xrandr not installed).")
        return 1
    sys.stdout.write(out if out.endswith("\n") else out + "\n")
    return 0


_ROTATIONS = ("normal", "left", "right", "inverted")


def display_usage() -> None:
    print(
        "Usage: azzio display <info|scale|resolution|refresh|rotate|primary|on|off|"
        "mirror|position> [args]\n"
        "\n"
        "Configure the display (xrandr) and the GLOBAL UI SCALE.\n"
        "\n"
        "  info                              Print the xrandr state.\n"
        "  scale [get | <factor>]            Get / set the global UI scale "
        + " / ".join(f"{s:g}" for s in DISPLAY_SCALE_OPTIONS) + ".\n"
        "  resolution <WxH> [output]         Set the resolution (xrandr --mode).\n"
        "  refresh <rate> [output]           Set the refresh rate (xrandr --rate).\n"
        "  rotate <normal|left|right|inverted> [output]   Orient an output.\n"
        "  primary <output>                  Make an output the primary monitor.\n"
        "  on <output> | off <output>        Enable / disable an output.\n"
        "  mirror <on|off>                   Mirror all outputs / extend.\n"
        "  position <out> <left-of|right-of|above|below> <other>   Arrange monitors.\n"
    )


def cmd_display(args: list[str]) -> int:
    """Dispatch `azzio display ...`."""
    if not args or args[0] in ("-h", "--help", "help"):
        display_usage()
        return 0
    verb = args[0]
    rest = args[1:]
    if verb == "info" or verb == "status":
        return _display_info()
    if verb == "scale":
        return cmd_scale(rest)
    if verb == "resolution":
        if not rest:
            _err("azzio display resolution: need <WxH> [output]")
            return 2
        out = _resolve_output(rest, 1)
        if not out:
            _err("azzio display: no connected output")
            return 1
        return _run_xrandr("--output", out, "--mode", rest[0])
    if verb == "refresh":
        if not rest:
            _err("azzio display refresh: need <rate> [output]")
            return 2
        out = _resolve_output(rest, 1)
        if not out:
            _err("azzio display: no connected output")
            return 1
        return _run_xrandr("--output", out, "--rate", rest[0])
    if verb == "rotate":
        if not rest or rest[0] not in _ROTATIONS:
            _err(f"azzio display rotate: need one of {', '.join(_ROTATIONS)}")
            return 2
        out = _resolve_output(rest, 1)
        if not out:
            _err("azzio display: no connected output")
            return 1
        return _run_xrandr("--output", out, "--rotate", rest[0])
    if verb == "primary":
        out = rest[0] if rest else _primary_output()
        if not out:
            _err("azzio display primary: need an output name")
            return 2
        return _run_xrandr("--output", out, "--primary")
    if verb == "on":
        out = rest[0] if rest else _primary_output()
        if not out:
            _err("azzio display on: need an output name")
            return 2
        return _run_xrandr("--output", out, "--auto")
    if verb == "off":
        if not rest:
            _err("azzio display off: need an output name")
            return 2
        return _run_xrandr("--output", rest[0], "--off")
    if verb == "mirror":
        if not rest or rest[0] not in ("on", "off"):
            _err("azzio display mirror: need on|off")
            return 2
        outs = _connected_outputs()
        prim = _primary_output()
        if not prim:
            _err("azzio display: no connected output")
            return 1
        if rest[0] == "on":
            # Point every non-primary output at the primary's position (same-origin = mirror).
            rc = 0
            for o in outs:
                if o == prim:
                    continue
                rc = _run_xrandr("--output", o, "--auto", "--same-as", prim) or rc
            return rc
        # extend: lay the others out to the right of the primary.
        rc = 0
        prev = prim
        for o in outs:
            if o == prim:
                continue
            rc = _run_xrandr("--output", o, "--auto", "--right-of", prev) or rc
            prev = o
        return rc
    if verb == "position":
        rels = ("left-of", "right-of", "above", "below")
        if len(rest) < 3 or rest[1] not in rels:
            _err(f"azzio display position: need <out> <{'|'.join(rels)}> <other>")
            return 2
        flag = "--" + rest[1]
        return _run_xrandr("--output", rest[0], flag, rest[2])
    _err(f"azzio display: unknown subcommand: {verb}")
    display_usage()
    return 2
