#!/usr/bin/env python3
"""azzio guest command line interface -- `azzio theme` (system-wide dark / white theme toggle).

WHAT "SYSTEM THEME" MEANS HERE. Azzio adopts the EXISTING freedesktop / GTK standard for
light-vs-dark so any downloaded application that already honours it is configured for free:

  * org.gnome.desktop.interface color-scheme -- the freedesktop "appearance" signal
    ('prefer-dark' | 'prefer-light'). GTK4/libadwaita apps and anything that reads the
    XDG settings portal follow this. Stored in dconf (gsettings), the single source of truth.
  * The GTK theme name + the "prefer dark" flag, written to the standard GTK config files
    (~/.config/gtk-3.0/settings.ini, ~/.config/gtk-4.0/settings.ini, ~/.gtkrc-2.0) so GTK3
    and GTK2 apps -- which do NOT all read color-scheme -- also switch. The dark theme is
    Adwaita-dark and the light theme Adwaita (both shipped by gnome-themes-extra), the
    reference GTK themes.

On top of that standard, `azzio theme` also flips the pieces that are NOT GTK and therefore
do not read color-scheme on their own: the OpenBox titlebar theme (Azzio <-> Azzio-Dark),
gedit's editor style scheme, VLC's Qt palette, and LibreWolf's reported system dark flag
(which also drives the Azzio timedate home page via prefers-color-scheme). Then it applies
everything LIVE (openbox --reconfigure, restart the menu daemon) so the running session
changes without a re-login.

THE KITTY TERMINAL IS DELIBERATELY EXEMPT. Per the Azzio design, kitty keeps its own look
regardless of the system theme -- `azzio theme` never touches kitty's config and never
signals it. (Everything else follows the theme.)

DARK IS THE DEFAULT. The ISO ships everything dark (skel + the live user); `azzio theme
--white` switches to the light look and `--dark` switches back. `azzio theme` with no
argument prints the current state. All state lives in per-user config + the user dconf, so
this runs WITHOUT sudo (it configures the user session, not the system).
"""

from __future__ import annotations

# BUNDLE_START

# The live user's home (matches openbox.HOME / the airootfs /home/main tree). The theme
# always configures the CURRENT user's session, so paths are resolved off ~ at runtime;
# HOME here is only the build-time default used when generating the shipped defaults.
_THEME_HOME = os.path.expanduser("~")

# The two GTK themes (shipped by gnome-themes-extra) and the two color-scheme values.
GTK_THEME_DARK = "Adwaita-dark"
GTK_THEME_LIGHT = "Adwaita"
COLOR_SCHEME_DARK = "prefer-dark"
COLOR_SCHEME_LIGHT = "prefer-light"
# The two OpenBox titlebar themes packages.openbox ships to ~/.themes (light = the classic
# Clearlooks-cyan "Azzio"; dark = "Azzio-Dark"). rc.xml's <theme><name> selects one.
OPENBOX_THEME_DARK = "Azzio-Dark"
OPENBOX_THEME_LIGHT = "Azzio"
# gedit 50 keeps TWO editor style-scheme keys (dark + light variant) and picks between them
# by the GTK dark flag automatically, so `azzio theme` does NOT flip a gedit scheme key --
# gedit follows the GTK theme the GTK settings.ini + gtk-theme gsetting already carry. (The
# two variant schemes -- 'oblivion' / 'classic' -- are seeded by the gedit gschema override.)


def _gsettings_set(schema: str, key: str, value: str) -> None:
    """Best-effort `gsettings set` (per-user dconf). Silent if gsettings/dconf or the
    schema is absent -- the settings.ini files below still carry the theme for GTK."""
    if _have("gsettings"):
        subprocess.run(["gsettings", "set", schema, key, value],
                       stderr=subprocess.DEVNULL, stdout=subprocess.DEVNULL, check=False)


def _gsettings_get(schema: str, key: str) -> str:
    """Best-effort `gsettings get`; returns the raw value (quotes stripped) or ""."""
    if not _have("gsettings"):
        return ""
    r = subprocess.run(["gsettings", "get", schema, key],
                       stderr=subprocess.DEVNULL, stdout=subprocess.PIPE)
    if r.returncode != 0:
        return ""
    return r.stdout.decode("utf-8", "replace").strip().strip("'\"")


def gtk3_settings_ini(dark: bool) -> str:
    """~/.config/gtk-3.0/settings.ini -- the GTK3 theme + prefer-dark flag. GTK3 apps
    (gedit and most downloaded GTK apps) read this at startup. Qt apps (Calamares, any
    downloaded Qt app) follow the SAME theme via QT_QPA_PLATFORMTHEME=gtk3 set in the
    OpenBox session environment (packages.openbox.openbox_environment), which points Qt at
    this GTK theme -- so they honour the toggle too, with no Qt-side theme config."""
    theme = GTK_THEME_DARK if dark else GTK_THEME_LIGHT
    prefer = 1 if dark else 0
    return (
        "# Azzio GTK3 theme. Generated by `azzio theme` (edit via the command, not\n"
        "# this file). gtk-application-prefer-dark-theme is the GTK3 dark switch.\n"
        "[Settings]\n"
        f"gtk-theme-name={theme}\n"
        f"gtk-application-prefer-dark-theme={prefer}\n"
        # The Azzio icon theme (inherits Adwaita) -- our folder/file/toolbar icons win, the rest
        # fall through to Adwaita. Shared by both light and dark (icon themes are not dark/light).
        "gtk-icon-theme-name=Azzio\n"
        # Show icons in menus (PROMPT file manager batch item 6). GTK3's gtk-menu-images defaults to
        # FALSE, which is why the file manager's "Open With" entries render without their app icons; setting
        # it true restores them (the file manager builds those items with xfce_gtk_image_menu_item, which
        # honours this GtkSetting). Harmless/desirable for every other GTK app's menus too.
        "gtk-menu-images=true\n"
    )


def gtk4_settings_ini(dark: bool) -> str:
    """~/.config/gtk-4.0/settings.ini -- same idea for GTK4 apps that read it directly."""
    theme = GTK_THEME_DARK if dark else GTK_THEME_LIGHT
    prefer = 1 if dark else 0
    return (
        "# Azzio GTK4 theme. Generated by `azzio theme`.\n"
        "[Settings]\n"
        f"gtk-theme-name={theme}\n"
        f"gtk-application-prefer-dark-theme={prefer}\n"
        # The Azzio icon theme (inherits Adwaita); see gtk3_settings_ini.
        "gtk-icon-theme-name=Azzio\n"
    )


def gtkrc2(dark: bool) -> str:
    """~/.gtkrc-2.0 -- the GTK2 theme name (older GTK2 apps read this)."""
    theme = GTK_THEME_DARK if dark else GTK_THEME_LIGHT
    return (
        "# Azzio GTK2 theme. Generated by `azzio theme`.\n"
        f'gtk-theme-name="{theme}"\n'
        # The Azzio icon theme (inherits Adwaita); see gtk3_settings_ini.
        'gtk-icon-theme-name="Azzio"\n'
    )


def _write_user_file(rel_path: str, content: str, mode: int = 0o644) -> None:
    """Write a file under the current user's home (creating parent dirs). Used for all
    the per-user theme config; no sudo (these are the user's own dotfiles)."""
    path = os.path.join(_THEME_HOME, rel_path)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    try:
        os.chmod(path, mode)
    except OSError:
        pass


def _retheme_openbox(dark: bool) -> None:
    """Rewrite the <theme><name> in ~/.config/openbox/rc.xml to the dark/light Azzio
    OpenBox theme and, if a live session is up, `openbox --reconfigure` so the titlebar
    changes immediately. The two theme names ("Azzio"/"Azzio-Dark") appear in rc.xml
    ONLY as the theme name, so a plain token swap is safe."""
    import re
    rc = os.path.join(_THEME_HOME, ".config/openbox/rc.xml")
    want = OPENBOX_THEME_DARK if dark else OPENBOX_THEME_LIGHT
    try:
        text = open(rc, encoding="utf-8").read()
    except OSError:
        return
    # Replace whichever Azzio theme name is currently in the <name> element. Match the
    # exact element so nothing else (desktop names etc.) is touched.
    new = re.sub(r"<name>Azzio(?:-Dark)?</name>", f"<name>{want}</name>", text, count=1)
    if new != text:
        with open(rc, "w", encoding="utf-8") as fh:
            fh.write(new)
    if os.environ.get("DISPLAY") and _have("openbox"):
        subprocess.run(["openbox", "--reconfigure"],
                       stderr=subprocess.DEVNULL, check=False)


def _restart_menu_daemon() -> None:
    """Restart the Azzio application-menu daemon so it re-reads the theme (it picks the
    palette from color-scheme at startup). Only if it is already running in this session."""
    bin_path = "/usr/local/lib/azzio-application-menu/azzio-application-menu-daemon"
    if not (os.environ.get("DISPLAY") and os.path.exists(bin_path)):
        return
    if _have("pkill"):
        subprocess.run(["pkill", "-x", "azzio-application-menu-daemon"],
                       stderr=subprocess.DEVNULL, check=False)
    # Relaunch detached so it survives this process; matches the OpenBox autostart line.
    try:
        subprocess.Popen(["setsid", bin_path],
                         stdin=subprocess.DEVNULL,
                         stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                         start_new_session=True)
    except OSError:
        pass


def _rewrite_line(path: str, key_prefix: str, new_line: str) -> None:
    """In the file at `path` (under the user's home), replace the FIRST line that starts
    (after optional whitespace) with `key_prefix` by `new_line`. No-op if the file or a
    matching line is absent (the app's shipped config already carries the default). Used to
    flip a single pref in an existing app config without rewriting the whole file."""
    full = os.path.join(_THEME_HOME, path) if not path.startswith("/") else path
    try:
        lines = open(full, encoding="utf-8").read().splitlines()
    except OSError:
        return
    changed = False
    for i, ln in enumerate(lines):
        if ln.lstrip().startswith(key_prefix):
            lines[i] = new_line
            changed = True
            break
    if changed:
        with open(full, "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines) + "\n")


def _retheme_vlc(dark: bool) -> None:
    """Flip VLC's qt-palette-mode in ~/.config/vlc/vlcrc (2 = dark, 1 = light). VLC reads it
    at next launch. No-op if vlcrc is absent (shipped default already carries the value)."""
    val = 2 if dark else 1
    _rewrite_line(".config/vlc/vlcrc", "qt-palette-mode=", f"qt-palette-mode={val}")


def _retheme_librewolf(dark: bool) -> None:
    """Flip LibreWolf's theme prefs in its overrides.cfg so the browser (and, via
    prefers-color-scheme, the timedate home page) follow the theme. LibreWolf applies them
    at next launch. No-op if the file is absent (shipped default already carries them)."""
    cfg = ".config/librewolf/librewolf/librewolf.overrides.cfg"
    theme_val = 0 if dark else 1
    sys_dark = 1 if dark else 0
    prefers_val = 0 if dark else 1
    _rewrite_line(cfg, 'defaultPref("browser.theme.toolbar-theme"',
                  f'defaultPref("browser.theme.toolbar-theme", {theme_val});')
    _rewrite_line(cfg, 'defaultPref("browser.theme.content-theme"',
                  f'defaultPref("browser.theme.content-theme", {theme_val});')
    _rewrite_line(cfg, 'defaultPref("ui.systemUsesDarkTheme"',
                  f'defaultPref("ui.systemUsesDarkTheme", {sys_dark});')
    _rewrite_line(cfg, 'defaultPref("layout.css.prefers-color-scheme.content-override"',
                  f'defaultPref("layout.css.prefers-color-scheme.content-override", {prefers_val});')


def apply_theme(dark: bool) -> int:
    """Apply the dark (default) or light system theme end-to-end: the freedesktop
    color-scheme + GTK theme (the standard downloaded apps read), then the non-GTK pieces
    (OpenBox titlebar, kitty, gedit, VLC, LibreWolf), then reload the live session."""
    # 1. The STANDARD signal downloaded apps read: color-scheme (dconf) + GTK theme files.
    _gsettings_set("org.gnome.desktop.interface", "color-scheme",
                   COLOR_SCHEME_DARK if dark else COLOR_SCHEME_LIGHT)
    _gsettings_set("org.gnome.desktop.interface", "gtk-theme",
                   GTK_THEME_DARK if dark else GTK_THEME_LIGHT)
    _write_user_file(".config/gtk-3.0/settings.ini", gtk3_settings_ini(dark))
    _write_user_file(".config/gtk-4.0/settings.ini", gtk4_settings_ini(dark))
    _write_user_file(".gtkrc-2.0", gtkrc2(dark))

    # 2. The non-GTK shipped apps + the OpenBox titlebar. (kitty is DELIBERATELY exempt --
    # it keeps its own look regardless of the system theme, so it is not touched here. gedit
    # is GTK and follows the GTK dark flag set in step 1, incl. its editor style scheme, so it
    # needs no explicit flip here.)
    _retheme_openbox(dark)
    _retheme_vlc(dark)
    _retheme_librewolf(dark)

    # 3. Apply live so the running session changes without a re-login. (VLC + LibreWolf pick
    # up their flipped config at their next launch; the menu daemon is restarted so it
    # re-reads the palette now.)
    _restart_menu_daemon()

    print(f"System theme set to {'dark' if dark else 'white'}.")
    return 0


def current_theme() -> str:
    """Return the current system theme as 'dark' or 'white', read from the standard
    signals (color-scheme first; else the GTK3 settings.ini prefer-dark flag)."""
    cs = _gsettings_get("org.gnome.desktop.interface", "color-scheme")
    if cs == COLOR_SCHEME_DARK:
        return "dark"
    if cs == COLOR_SCHEME_LIGHT:
        return "white"
    # Fall back to the GTK3 settings.ini prefer-dark flag.
    try:
        ini = open(os.path.join(_THEME_HOME, ".config/gtk-3.0/settings.ini"),
                   encoding="utf-8").read()
        for line in ini.splitlines():
            if line.strip().startswith("gtk-application-prefer-dark-theme"):
                return "dark" if line.strip().endswith("1") else "white"
    except OSError:
        pass
    # Default is dark (the Azzio default).
    return "dark"


def theme_status() -> int:
    """Print the current system theme (the bare `azzio theme` behaviour)."""
    cur = current_theme()
    gtk = _gsettings_get("org.gnome.desktop.interface", "gtk-theme") or (
        GTK_THEME_DARK if cur == "dark" else GTK_THEME_LIGHT)
    print(f"System theme: {cur}")
    print(f"  color-scheme: {COLOR_SCHEME_DARK if cur == 'dark' else COLOR_SCHEME_LIGHT}")
    print(f"  gtk-theme:    {gtk}")
    print(f"  openbox:      {OPENBOX_THEME_DARK if cur == 'dark' else OPENBOX_THEME_LIGHT}")
    return 0


def theme_usage() -> None:
    print(
        "Usage: azzio theme [--dark|-d | --white|-w]\n"
        "\n"
        "Set the system-wide colour theme (dark is the default). Every shipped\n"
        "application and the OpenBox titlebar follow it, and it is stored in the\n"
        "freedesktop color-scheme standard so downloaded apps that honour that\n"
        "standard are configured too.\n"
        "\n"
        "  --dark, -d    Dark theme (the default).\n"
        "  --white, -w   White (light) theme.\n"
        "  --help        Show this help.\n"
        "  (no option)   Print the current theme.\n"
    )


def cmd_theme(args: list[str]) -> int:
    """Dispatch `azzio theme ...`. No option -> print status; --dark/-d, --white/-w set
    the theme; --help/-h prints usage."""
    if not args:
        return theme_status()
    opt = args[0]
    if opt in ("--dark", "-d"):
        return apply_theme(dark=True)
    if opt in ("--white", "-w"):
        return apply_theme(dark=False)
    if opt in ("--help", "-h", "help"):
        theme_usage()
        return 0
    _err(f"azzio theme: unknown option: {opt}")
    theme_usage()
    return 2
