"""VLC configuration modification -- suppress the first-run "metadata network access" dialog.

On its very first launch VLC (the media player Azzio ships) pops a modal privacy
dialog: "Allow metadata network access?" (it wants to phone out to fetch album art /
codec info). The default answer is No, and Azzio wants that answer taken silently --
the dialog should NEVER appear. Two prefs in VLC's config file (~/.config/vlc/vlcrc)
control this, and we set BOTH.

VLC ALSO follows the system theme here: qt-palette-mode (VLC 3.0.20+) is VLC's dark/light
switch (2 = dark, 1 = light, 0 = system). Azzio ships it DARK by default (matching the
system dark default); `azzio theme --white` rewrites it to 1 (light) and --dark back. VLC
reads this from the same vlcrc. See vlcrc(dark).

The privacy prefs:

  * qt-privacy-ask = 0      [qt] section. This is THE switch that shows the first-run
                            privacy dialog. VLC ships it =1 (ask on first run); 0 means
                            "already asked, do not show it". Setting it to 0 is what makes
                            the dialog never appear.
  * metadata-network-access = 0   [core] section. The actual choice the dialog would set.
                            VLC's built-in default is already 0 (No), but we pin it
                            explicitly so the "No" answer is recorded regardless of the
                            dialog -- belt-and-braces so network metadata fetching stays
                            OFF even though we also suppressed the prompt.

WHY A PARTIAL vlcrc IS ENOUGH. vlcrc is an INI file (`[section]` headers, `key=value`
lines). VLC reads it OVER its built-in defaults -- any key we omit keeps VLC's default,
any key we set wins. So we ship only the two sections/keys we override (exactly the
librewolf.overrides.cfg approach), not a full dumped vlcrc. The section headers must
match VLC's own (`[qt]`, `[core]`) or the keys are ignored, so those are pinned here.

WHERE IT GOES. ~/.config/vlc/vlcrc for the live user (compiler.py chowns it 1000:998
and mirrors it into /etc/skel so a Calamares-created user inherits the same setting).
VLC writes this same file itself when the user changes a preference; our shipped copy
just pre-seeds the two privacy keys so the dialog is gone from the very first launch.

Pure standard library (returns a string). compiler.py iterates emit_plan() exactly like
packages/librewolf -- one HOME file, owner="home".
"""

from __future__ import annotations

# The live user's home (matches openbox.HOME / the airootfs /home/main tree).
HOME = "/home/main"

# WHERE VLC READS ITS CONFIG: ~/.config/vlc/vlcrc (XDG_CONFIG_HOME defaults to
# ~/.config, which the OpenBox session sets). Single source of truth for the path;
# emit_plan() ships the file here and compiler.py mirrors it into /etc/skel.
VLCRC_PATH = f"{HOME}/.config/vlc/vlcrc"

# VLC's qt-palette-mode values (VLC 3.0.20+): 2 = dark, 1 = light, 0 = system. Azzio
# defaults DARK; `azzio theme --white` rewrites the line to VLC_PALETTE_LIGHT.
VLC_PALETTE_DARK = 2
VLC_PALETTE_LIGHT = 1


def vlcrc(dark: bool = True) -> str:
    """Return the partial ~/.config/vlc/vlcrc that suppresses the first-run metadata
    privacy dialog AND sets VLC's dark/light palette (dark by default) (see the module
    docstring).

    Only the overridden sections/keys are written; VLC merges them over its built-in
    defaults, so everything else stays stock. The `[qt]`/`[core]` headers must match VLC's
    own section names or the keys are ignored."""
    palette = VLC_PALETTE_DARK if dark else VLC_PALETTE_LIGHT
    return f"""\
# Azzio VLC overrides -- suppress the first-run "Allow metadata network access?"
# dialog (default No, taken silently) and follow the system theme. Generated by
# packages/vlc (edit the Python, not this file). VLC reads these keys OVER its built-in
# defaults; every other VLC setting is left exactly as VLC ships it.

[qt] # Qt interface
# Do NOT show the first-run privacy/metadata dialog. VLC ships this =1 (ask on first
# run); 0 means "already asked" so the dialog never appears.
qt-privacy-ask=0
# Dark/light interface (VLC 3.0.20+): 2 = dark, 1 = light, 0 = system. Azzio defaults
# dark to match the system theme; `azzio theme --white` flips this to 1.
qt-palette-mode={palette}

[core] # core program
# Network access for metadata (album art / codec info) stays OFF -- the "No" the
# suppressed dialog would have defaulted to. (VLC's built-in default is already 0;
# pinned here so the answer is recorded regardless of the dialog.)
metadata-network-access=0
"""


# --- Emit plan --------------------------------------------------------------
# Declarative map (builder -> dest -> mode -> owner), the same shape compiler.py
# iterates for packages/openbox and packages/librewolf. One HOME file (owner="home"):
# compiler.py chowns it 1000:998 with the rest of /home/main AND mirrors it into
# /etc/skel so a Calamares-created user inherits the same privacy default. Mode 0644.
_CONF = 0o644


def emit_plan() -> list[dict]:
    """Return the emit plan for the VLC override: a single HOME file at ~/.config/vlc/vlcrc.

    Shape matches librewolf.emit_plan() (builder/dest/mode/owner) so compiler.py can emit
    it with the same loop (and skel-mirror the home file). Returns a FRESH dict so a
    caller cannot mutate module state."""
    return [
        {
            "builder": vlcrc,
            "dest": VLCRC_PATH,
            "mode": _CONF,
            "owner": "home",
        },
    ]
